# ---------------------------------------------------------------------
# Kaitai struct definition for: Nasdaq NasdaqCanada Chixmd AsciiItch v3.4.1.23
#
# Protocol:
#   Organization: National Association of Securities Dealers Automated Quotations (Nasdaq)
#   Protocol: CHIXMD Market Data
#   Encoding: Ascii Itch
#   Version: 3.4.1.23
#   Date: 10/08/2025
#   Specification: Nasdaq Canada Market Data Specification - CHIXMD 3.4 V1.23.pdf
#
# Script:
#   Generator: 1.0.0.0
#   License: Public/GPLv3
#   Authors: Omi Developers
#
# Copyright (c) 2026 Scaled Sources LLC.  https://www.scaledsources.com
#
# This kaitai struct definition is contributed to The Open Markets Initiative under
# the license noted above.
#
# The protocol compiler technologies used to produce this file
# are the subject of patents owned by Scaled Sources LLC.  Those patent
# rights are retained and are not transferred by this contribution:
#   https://patents.google.com/patent/US20240129382A1/en
#   https://patents.google.com/patent/US20240419416A1/en
#
# Open Markets Initiative website:
#   https://openmarketsinitiative.com
# ---------------------------------------------------------------------

meta:
  id: nasdaq_nasdaqcanada_chixmd_asciiitch_v3_4_1_23_client
  title: Nasdaq NasdaqCanada Chixmd AsciiItch v3.4.1.23
  license: GPL-3.0
  endian: be

doc: 'National Association of Securities Dealers Automated Quotations (Nasdaq) Nasdaq Canada CHIXMD Market Data AsciiItch v3.4.1.23'
doc-ref:
  - https://www.nasdaq.com/products/north-american-markets/canada/connectivity
  - https://www.nasdaq.com/docs/2026/01/20/Nasdaq%20Canada%20Market%20Data%20Specification%20-%20CHIXMD%203.4%20V1.23.pdf

seq:
  - id: client_packet_header
    type: client_packet_header_struct
    doc: 'SoupTcp Packet Header sent by the client'
  - id: client_payload
    type:
      switch-on: client_packet_header.client_packet_type
      cases:
        'client_packet_type::debug_packet': debug_packet
        'client_packet_type::login_request_packet': login_request_packet
  - id: soup_lf
    type: u1
    doc: 'Terminating line feed character'

types:
  client_packet_header_struct:
    seq:
      - id: client_packet_type
        type: u1
        enum: client_packet_type
        doc: 'Code identifying this packet type'
  debug_packet:
    seq:
      - id: text
        type: str
        size: 1
        encoding: ASCII
        doc: 'Free form human readable text'
  login_request_packet:
    seq:
      - id: username
        type: str
        size: 6
        encoding: ASCII
        pad-right: 0x20
        doc: 'Session username'
      - id: password
        type: str
        size: 10
        encoding: ASCII
        pad-right: 0x20
        doc: 'Login password'
      - id: requested_session
        type: str
        size: 10
        encoding: ASCII
        pad-right: 0x20
        doc: 'Requested session ID. For initial login leaving this field blank is recommended; for subsequent logins inclusion of the session ID is recommended'
      - id: requested_sequence_number
        type: str
        size: 10
        encoding: ASCII
        pad-right: 0x20
        doc: 'Sequence you wish the feed to start from (next expected). 1 indicates the beginning of the day. 0 indicates the last message generated by the system, bypassing recovery'

enums:
  client_packet_type:
    0x2b:
      id: 'debug_packet'
      doc: 'SoupTcp Debug Packet'
    0x4c:
      id: 'login_request_packet'
      doc: 'SoupTcp Login Request Packet'
    0x52:
      id: 'client_heartbeat_packet'
      doc: 'SoupTcp Client Heartbeat Packet'
    0x4f:
      id: 'logout_request_packet'
      doc: 'SoupTcp Logout Request Packet'
  server_packet_type:
    0x2b:
      id: 'debug_packet'
      doc: 'SoupTcp Debug Packet'
    0x41:
      id: 'login_accepted_packet'
      doc: 'SoupTcp Login Accepted Packet'
    0x4a:
      id: 'login_rejected_packet'
      doc: 'SoupTcp Login Rejected Packet'
    0x53:
      id: 'sequenced_data_packet'
      doc: 'Sequenced Data Packet'
    0x48:
      id: 'server_heartbeat_packet'
      doc: 'SoupTcp Server Heartbeat Packet'
  reject_reason_code:
    0x41:
      id: 'invalid_username_or_password'
      doc: 'Invalid username/password'
    0x53:
      id: 'invalid_session'
      doc: 'Invalid session'
  message_type:
    0x41:
      id: 'add_order_message'
      doc: 'An Add Order Message indicates that CXC or CX2 has accepted a visible order into the book. It includes a day-unique Order Reference key assigned to the order. The issuing of an Add Order Message is not necessarily always for a new order (see Modification of Existing Orders). Not applicable to CXD.'
    0x61:
      id: 'long_form_add_order_message'
      doc: 'An Add Order Message indicates that CXC or CX2 has accepted a visible order into the book. It includes a day-unique Order Reference key assigned to the order. The issuing of an Add Order Message is not necessarily always for a new order (see Modification of Existing Orders). Not applicable to CXD. Long form messages are used when either the price or size is larger than the standard messages can permit.'
    0x45:
      id: 'order_execution_message'
      doc: 'An Order Execution Message is sent whenever an order on the book is executed in whole or in part. Not applicable to CXD.'
    0x65:
      id: 'long_form_order_execution_message'
      doc: 'An Order Execution Message is sent whenever an order on the book is executed in whole or in part. Not applicable to CXD. Long form messages are used when either the price or size is larger than the standard messages can permit.'
    0x58:
      id: 'order_cancel_message'
      doc: 'An Order Cancel Message is sent whenever an order on the book is fully canceled, its quantity revised down or when a pegged order is re-priced. Not applicable to CXD.'
    0x78:
      id: 'long_form_order_cancel_message'
      doc: 'An Order Cancel Message is sent whenever an order on the book is fully canceled, its quantity revised down or when a pegged order is re-priced. Not applicable to CXD. Long form messages are used when either the price or size is larger than the standard messages can permit.'
    0x50:
      id: 'trade_message'
      doc: 'A Trade Message is sent when a trade occurs against order quantity not visible on the book (i.e. a fully or partially hidden order). They do not affect the book. The Order Reference is always 0 and the Buy/Sell indicator B.'
    0x70:
      id: 'long_form_trade_message'
      doc: 'A Trade Message is sent when a trade occurs against order quantity not visible on the book (i.e. a fully or partially hidden order). They do not affect the book. The Order Reference is always 0 and the Buy/Sell indicator B. Long form messages are used when either the price or size is larger than the standard messages can permit.'
    0x42:
      id: 'broken_trade_message'
      doc: 'A Broken Trade message is sent whenever an execution is broken. A Broken Trade is final; once a trade is broken it cannot be reinstated.'
    0x53:
      id: 'system_event_message'
      doc: 'The system event message type is used to indicate a market state event.'
    0x48:
      id: 'stock_status_message'
      doc: 'This message indicates the current trading status of a stock. At the start of day, the feed will send out a stock status message for each of the symbols trading on CXC, CX2 and CXD. Subsequently, stock status messages will be sent when a stock is halted or is released for trading.'
  buy_sell_indicator:
    0x42:
      id: 'buy'
      doc: 'Buy Order'
    0x53:
      id: 'sell'
      doc: 'Sell Order'
  trade_attribute:
    0x42:
      id: 'bypass'
      doc: 'Bypass Intentional Crosses Only Trade Message'
    0x43:
      id: 'market_on_close_or_cxd_conditional'
      doc: 'Market On Close On The Order Execution Message Cxd Conditional On The Trade Message'
    0x4c:
      id: 'melo'
      doc: 'Melo Trade Message'
    0x50:
      id: 'cxd_pure_stream'
      doc: 'Cxd Pure Stream Trade Message'
  cross_type:
    0x49:
      id: 'internal_field'
      doc: 'Internal'
    0x42:
      id: 'basis'
      doc: 'Basis'
    0x43:
      id: 'contingent'
      doc: 'Contingent'
    0x56:
      id: 'vwap'
      doc: 'Vwap'
    0x58:
      id: 'intentional_cross'
      doc: 'Intentional Cross'
    0x44:
      id: 'derivative_related'
      doc: 'Derivative Related'
    0x4e:
      id: 'net_asset_value'
      doc: 'Net Asset Value'
  settlement_terms:
    0x54:
      id: 'cash_today'
      doc: 'Cash Today'
    0x44:
      id: 'delayed_delivery'
      doc: 'Delayed Delivery'
  event_code:
    0x4f:
      id: 'start_of_messages'
      doc: 'First Message Of The Day'
    0x53:
      id: 'start_of_nasdaq_canada_trading_session'
      doc: 'Start Of Nasdaq Canada Trading Session'
    0x51:
      id: 'start_of_primary_market_trading_session'
      doc: 'Start Of Primary Market Trading Session'
    0x4d:
      id: 'end_of_primary_market_trading_session'
      doc: 'End Of Primary Market Trading Session Indicates That Pegged Orders Are No Longer Available For Execution'
    0x45:
      id: 'end_of_system_hours'
      doc: 'End Of System Hours Nasdaq Canada Is Closed And Not Accepting Orders It Is Still Possible To Receive Broken Trade Messages And Order Cancel Messages'
    0x43:
      id: 'end_of_messages'
      doc: 'End Of Messages Last Message Of The Day'
    0x57:
      id: 'market_wide_circuit_breaker_halt'
      doc: 'Trading Halted Due To Market Wide Circuit Breaker'
    0x52:
      id: 'market_wide_circuit_breaker_resumption'
      doc: 'Trading Resumed Following Market Wide Circuit Breaker'
  trading_state:
    0x48:
      id: 'halted'
      doc: 'Halted'
    0x54:
      id: 'trading'
      doc: 'Trading'
  listing_market:
    0x54:
      id: 'tsx'
      doc: 'Tsx'
    0x56:
      id: 'tsx_venture'
      doc: 'Tsx Venture'
    0x43:
      id: 'cse'
      doc: 'Cse'
    0x4e:
      id: 'neo'
      doc: 'Neo'
  gef_eligible:
    0x59:
      id: 'gef_eligible'
      doc: 'Gef Eligible'
    0x4e:
      id: 'not_gef_eligible'
      doc: 'Not Gef Eligible'

