# ---------------------------------------------------------------------
# Kaitai struct definition for: Miax OnyxFutures ExpressInterface Fei v1.0.c
#
# Protocol:
#   Organization: Miami International Holdings
#   Protocol: Express Interface
#   Encoding: Futures Express Interface
#   Version: 1.0.c
#   Date: 5/22/2025
#   Specification: onyx_futures_express_interface_fei_v1.0c.pdf
#
# Script:
#   Generator: 1.0.0.0
#   License: Public/GPLv3
#   Authors: Omi Developers
#
# Copyright (c) 2026 Scaled Sources LLC.  https://www.scaledsources.com
#
# This kaitai struct definition is contributed to The Open Markets Initiative under
# the license noted above.
#
# The protocol compiler technologies used to produce this file
# are the subject of patents owned by Scaled Sources LLC.  Those patent
# rights are retained and are not transferred by this contribution:
#   https://patents.google.com/patent/US20240129382A1/en
#   https://patents.google.com/patent/US20240419416A1/en
#
# Open Markets Initiative website:
#   https://openmarketsinitiative.com
# ---------------------------------------------------------------------

meta:
  id: miax_onyxfutures_expressinterface_fei_v1_0_c
  title: Miax OnyxFutures ExpressInterface Fei v1.0.c
  license: GPL-3.0
  endian: le

doc: 'Miami International Holdings MIAX Futures Onyx Express Interface Fei v1.0.c'
doc-ref: https://www.miaxglobal.com/markets/futures/miax-futures/onyx-interface-specifications

seq:
  - id: sesm_tcp_packet
    type: sesm_tcp_packet_struct
    repeat: eos
    doc: 'SesM Tcp Packet'

types:
  sesm_tcp_packet_struct:
    seq:
      - id: sesm_packet_header
        type: sesm_packet_header
        doc: 'SesM packet header'
      - id: sesm_payload
        size: sesm_packet_header.sesm_packet_length + 2 - 3
        type:
          switch-on: sesm_packet_header.sesm_packet_type
          cases:
            'sesm_packet_type::sequenced_data_packet': sequenced_data_packet
            'sesm_packet_type::unsequenced_data_packet': unsequenced_data_packet
            'sesm_packet_type::login_request': login_request
            'sesm_packet_type::login_response': login_response
            'sesm_packet_type::retransmission_request': retransmission_request
            'sesm_packet_type::logout_request': logout_request
            'sesm_packet_type::goodbye_packet': goodbye_packet
  sesm_packet_header:
    seq:
      - id: sesm_packet_length
        type: u2
        doc: 'The length of rest of the packet'
      - id: sesm_packet_type
        type: u1
        enum: sesm_packet_type
        doc: 'Code identifying this packet type'
  sequenced_data_packet:
    seq:
      - id: sequence_number
        type: u8
        doc: 'Sequence number of this sequenced data packet'
      - id: sequenced_message_type
        type: str
        size: 2
        encoding: ASCII
        doc: 'SesM sequenced message type'
      - id: sequenced_message
        size: _parent.sesm_packet_header.sesm_packet_length - 11
        type:
          switch-on: sequenced_message_type
          cases:
            '"NR"': new_order_response_message
            '"MR"': modify_order_response
            '"CR"': cancel_order_response
            '"XR"': mass_cancel_response
            '"SR"': strategy_creation_response_message
            '"SN"': system_state_notification_message
            '"O1"': new_order_notification
            '"MN"': modify_order_notification
            '"XN"': cancel_reduce_size_order_notification
            '"OS"': order_status_update_notification
            '"EN"': simple_execution_notification
            '"CN"': complex_execution_notification
  new_order_response_message:
    seq:
      - id: matching_engine
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the Matching Engine. Nanoseconds since Unix epoch'
      - id: mp_id
        type: str
        size: 5
        encoding: ASCII
        pad-right: 0x20
        doc: 'Five character MPID of the Firm whose order is sent'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order ID'
      - id: instrument_id_binary_u_4
        type: u4
        doc: 'Instrument ID mapped to a given Instrument assigned by MIAX Futures Onyx'
      - id: order_id
        type: u8
        doc: 'Exchange assigned unique order ID when order is'
      - id: status
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Note,RejectRe'
      - id: reserved_10
        size: 10
        doc: 'Reserved for future use'
  modify_order_response:
    seq:
      - id: matching_engine_time
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the Matching Engine. Nanoseconds since Unix epoch'
      - id: mp_id
        type: str
        size: 5
        encoding: ASCII
        pad-right: 0x20
        doc: 'Five character MPID of the Firm whose order is sent'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order ID'
      - id: original_client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Target Client Order ID that is being modified'
      - id: instrument_id_binary_u_4
        type: u4
        doc: 'Instrument ID mapped to a given Instrument assigned by MIAX Futures Onyx'
      - id: order_id
        type: u8
        doc: 'Exchange assigned unique order ID when order is'
      - id: leaves_qty
        type: u4
        doc: 'Size of the order that is still open'
      - id: status
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Note,RejectRe'
      - id: reserved_10
        size: 10
        doc: 'Reserved for future use'
  cancel_order_response:
    seq:
      - id: matching_engine_time
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the Matching Engine. Nanoseconds since Unix epoch'
      - id: mp_id
        type: str
        size: 5
        encoding: ASCII
        pad-right: 0x20
        doc: 'Five character MPID of the Firm whose order is sent'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order ID'
      - id: original_client_order
        type: str
        size: 20
        encoding: ASCII
        doc: 'As specified in the Cancel Order Request'
      - id: instrument_id_binary_u_4
        type: u4
        doc: 'Instrument ID mapped to a given Instrument assigned by MIAX Futures Onyx'
      - id: order_id
        type: u8
        doc: 'Exchange assigned unique order ID when order is'
      - id: status
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Note,RejectRe'
  mass_cancel_response:
    seq:
      - id: matching_engine_time
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the Matching Engine. Nanoseconds since Unix epoch'
      - id: mp_id
        type: str
        size: 5
        encoding: ASCII
        pad-right: 0x20
        doc: 'Five character MPID of the Firm whose order is sent'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order ID'
      - id: status
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Note,RejectRe'
      - id: reserved_10
        size: 10
        doc: 'Reserved for future use'
  strategy_creation_response_message:
    seq:
      - id: matching_engine_time
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the Matching Engine. Nanoseconds since Unix epoch'
      - id: mp_id
        type: str
        size: 5
        encoding: ASCII
        pad-right: 0x20
        doc: 'Five character MPID of the Firm whose order is sent'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order ID'
      - id: instrument_id_string_20
        type: str
        size: 20
        encoding: ASCII
        doc: 'Instrument ID for the requested strategy'
      - id: status
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Note,RejectRe'
      - id: reserved_16
        size: 16
        doc: 'Reserved for future use'
  system_state_notification_message:
    seq:
      - id: matching_engine_time
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the Matching Engine. Nanoseconds since Unix epoch'
      - id: version
        type: str
        size: 8
        encoding: ASCII
        pad-right: 0x20
        doc: 'FEI version'
      - id: session_id
        type: u1
        doc: 'MIAX Futures Onyx assigned ID for the current trading session for the Matching Engine'
      - id: system_status
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'System Status'
      - id: reserved_8
        size: 8
        doc: 'Reserved for future use'
  new_order_notification:
    seq:
      - id: matching_engine_time
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the Matching Engine. Nanoseconds since Unix epoch'
      - id: mp_id
        type: str
        size: 5
        encoding: ASCII
        pad-right: 0x20
        doc: 'Five character MPID of the Firm whose order is sent'
      - id: order_id
        type: u8
        doc: 'Exchange assigned unique order ID when order is'
      - id: client_send_time
        type: nanosecond_timestamp
        doc: 'Firm’s send time. Nanoseconds since Unix epoch'
      - id: operator_id
        type: str
        size: 18
        encoding: ASCII
        doc: 'This must contain a 2 to 18 character Operator'
      - id: operator_location
        type: str
        size: 6
        encoding: ASCII
        doc: 'The location associated with Operator ID'
      - id: account
        type: str
        size: 16
        encoding: ASCII
        doc: 'Customer ID defined by the firm'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order ID'
      - id: instrument_id_binary_u_4
        type: u4
        doc: 'Instrument ID mapped to a given Instrument assigned by MIAX Futures Onyx'
      - id: price
        type: decimal_s8_9
        doc: 'Limit price of the order. Implied decimal with scale 1e-9'
      - id: stop_order_trigger_price
        type: decimal_s8_9
        doc: 'Stop Order Trigger Price, Ignored if not a stop order. Implied decimal with scale 1e-9'
      - id: size_binary_u_4
        type: u4
        doc: 'Number of contracts to buy/sell'
      - id: order_instructions
        type: order_instructions
        doc: 'Order Instructions'
      - id: time_in_force
        type: u1
        enum: time_in_force
        doc: 'Time in Force'
      - id: order_type
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Order Type'
      - id: self_trade_protection
        type: self_trade_protection
        doc: 'Self Trade Protection'
      - id: self_trade_protection_group
        type: str
        size: 2
        encoding: ASCII
        doc: 'Customer specified protection group, if empty string, group is not specified'
      - id: purge_group
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Customer specified purge group'
      - id: customer_order_handling_instruction
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Customer Order Handling Instruction:'
      - id: additional_order_indicators
        type: additional_order_indicators
        doc: 'Additional Order Indicators Flags'
      - id: min_qty
        type: u4
        doc: 'Minimum fill quantity'
      - id: order_expiry_date
        type: u2
        doc: 'GTD Order Expiry date, set to zero for all other tifs'
      - id: trading_collar_dollar_value
        type: decimal_s8_9
        doc: 'Custom Dollar Value Trading Collar Protection. Implied decimal with scale 1e-9'
      - id: cti_code
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'CTI Code values'
      - id: text_memo
        type: str
        size: 20
        encoding: ASCII
        doc: 'Clearing Text Memo'
      - id: reserved_32
        size: 32
        doc: 'Reserved for future use'
  order_instructions:
    meta:
      bit-endian: le
    seq:
      - id: side
        type: b1
        doc: 'Side'
      - id: unused_15
        type: b15
        doc: 'Reserved for future use'
  self_trade_protection:
    meta:
      bit-endian: le
    seq:
      - id: self_trade_protection_level
        type: b3
        doc: 'Self Trade Protection Level'
      - id: self_trade_protection_instruction
        type: b3
        doc: 'Self Trade Protection Instruction'
      - id: unused_2
        type: b2
        doc: 'Reserved for future use'
  additional_order_indicators:
    meta:
      bit-endian: le
    seq:
      - id: customer_of_firm_designation
        type: b1
        doc: 'Customer of Firm Designation'
      - id: manual_order_indicator
        type: b1
        doc: 'Manual Order Indicator'
      - id: open_close_position_indicator
        type: b1
        doc: 'Open Close position Indicator'
      - id: unused_5
        type: b5
        doc: 'Reserved for future use'
  modify_order_notification:
    seq:
      - id: matching_engine_time
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the Matching Engine. Nanoseconds since Unix epoch'
      - id: mp_id
        type: str
        size: 5
        encoding: ASCII
        pad-right: 0x20
        doc: 'Five character MPID of the Firm whose order is sent'
      - id: order_id
        type: u8
        doc: 'Exchange assigned unique order ID when order is'
      - id: client_send_time
        type: nanosecond_timestamp
        doc: 'Firm’s send time. Nanoseconds since Unix epoch'
      - id: leaves_qty
        type: u4
        doc: 'Size of the order that is still open'
      - id: operator_id
        type: str
        size: 18
        encoding: ASCII
        doc: 'This must contain a 2 to 18 character Operator'
      - id: operator_location
        type: str
        size: 6
        encoding: ASCII
        doc: 'The location associated with Operator ID'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order ID'
      - id: original_client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Target Client Order ID that is being modified'
      - id: instrument_id_binary_u_4
        type: u4
        doc: 'Instrument ID mapped to a given Instrument assigned by MIAX Futures Onyx'
      - id: price
        type: decimal_s8_9
        doc: 'Limit price of the order. Implied decimal with scale 1e-9'
      - id: stop_order_trigger_price
        type: decimal_s8_9
        doc: 'Stop Order Trigger Price, Ignored if not a stop order. Implied decimal with scale 1e-9'
      - id: size_binary_s_4
        type: s4
        doc: 'New size of the order if size is being modified'
      - id: order_expiry_date
        type: u2
        doc: 'GTD Order Expiry date, set to zero for all other tifs'
      - id: self_trade_protection_group
        type: str
        size: 2
        encoding: ASCII
        doc: 'Customer specified protection group, if empty string, group is not specified'
      - id: purge_group
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Customer specified purge group'
      - id: customer_order_handling_instruction
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Customer Order Handling Instruction:'
      - id: additional_order_indicators
        type: additional_order_indicators
        doc: 'Additional Order Indicators Flags'
      - id: reserved_32
        size: 32
        doc: 'Reserved for future use'
  cancel_reduce_size_order_notification:
    seq:
      - id: matching_engine_time
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the Matching Engine. Nanoseconds since Unix epoch'
      - id: mp_id
        type: str
        size: 5
        encoding: ASCII
        pad-right: 0x20
        doc: 'Five character MPID of the Firm whose order is sent'
      - id: operator_id
        type: str
        size: 18
        encoding: ASCII
        doc: 'This must contain a 2 to 18 character Operator'
      - id: operator_location
        type: str
        size: 6
        encoding: ASCII
        doc: 'The location associated with Operator ID'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order ID'
      - id: instrument_id_binary_u_4
        type: u4
        doc: 'Instrument ID mapped to a given Instrument assigned by MIAX Futures Onyx'
      - id: order_id
        type: u8
        doc: 'Exchange assigned unique order ID when order is'
      - id: client_send_time
        type: nanosecond_timestamp
        doc: 'Firm’s send time. Nanoseconds since Unix epoch'
      - id: leaves_qty
        type: u4
        doc: 'Size of the order that is still open'
      - id: cancel_reason
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Note,Can'
      - id: last_price
        type: decimal_s8_9
        doc: 'Match price if the order had not been prevented. Implied decimal with scale 1e-9'
      - id: last_size
        type: u4
        doc: 'Number of contracts that would have matched if the order had not been prevented from execution'
      - id: reserved_8
        size: 8
        doc: 'Reserved for future use'
  order_status_update_notification:
    seq:
      - id: matching_engine_time
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the Matching Engine. Nanoseconds since Unix epoch'
      - id: instrument_id_binary_u_4
        type: u4
        doc: 'Instrument ID mapped to a given Instrument assigned by MIAX Futures Onyx'
      - id: order_id
        type: u8
        doc: 'Exchange assigned unique order ID when order is'
      - id: update_status
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Order status update'
      - id: reserved_32
        size: 32
        doc: 'Reserved for future use'
  simple_execution_notification:
    seq:
      - id: matching_engine_time
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the Matching Engine. Nanoseconds since Unix epoch'
      - id: mp_id
        type: str
        size: 5
        encoding: ASCII
        pad-right: 0x20
        doc: 'Five character MPID of the Firm whose order is sent'
      - id: operator_id
        type: str
        size: 18
        encoding: ASCII
        doc: 'This must contain a 2 to 18 character Operator'
      - id: operator_location
        type: str
        size: 6
        encoding: ASCII
        doc: 'The location associated with Operator ID'
      - id: instrument_id_binary_u_4
        type: u4
        doc: 'Instrument ID mapped to a given Instrument assigned by MIAX Futures Onyx'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order ID'
      - id: simple_trade_id
        type: u8
        doc: 'Exchange assigned unique Simple Trade ID. See'
      - id: complex_trade_id
        type: u8
        doc: 'Exchange assigned unique Complex Trade ID'
      - id: execution_id
        type: u8
        doc: 'Exchange assigned unique Execution ID. See'
      - id: trade_date
        type: u2
        doc: 'Business Trade Date'
      - id: correction_number
        type: u1
        doc: 'Trade correction number'
      - id: trade_status
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Possible values:'
      - id: last_price
        type: decimal_s8_9
        doc: 'Match price if the order had not been prevented. Implied decimal with scale 1e-9'
      - id: last_size
        type: u4
        doc: 'Number of contracts that would have matched if the order had not been prevented from execution'
      - id: order_instructions
        type: order_instructions
        doc: 'Order Instructions'
      - id: cti_code
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'CTI Code values'
      - id: text_memo
        type: str
        size: 20
        encoding: ASCII
        doc: 'Clearing Text Memo'
      - id: liquidity_indicator
        type: str
        size: 3
        encoding: ASCII
        doc: 'Please refer to MIAX Onyx Futures Liquidity'
      - id: reserved_32
        size: 32
        doc: 'Reserved for future use'
  complex_execution_notification:
    seq:
      - id: matching_engine_time
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the Matching Engine. Nanoseconds since Unix epoch'
      - id: mp_id
        type: str
        size: 5
        encoding: ASCII
        pad-right: 0x20
        doc: 'Five character MPID of the Firm whose order is sent'
      - id: instrument_id_binary_u_4
        type: u4
        doc: 'Instrument ID mapped to a given Instrument assigned by MIAX Futures Onyx'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order ID'
      - id: complex_trade_id
        type: u8
        doc: 'Exchange assigned unique Complex Trade ID'
      - id: trade_date
        type: u2
        doc: 'Business Trade Date'
      - id: last_net_price
        type: decimal_s8_9
        doc: 'Net Price of this execution. Implied decimal with scale 1e-9'
      - id: last_size
        type: u4
        doc: 'Number of contracts that would have matched if the order had not been prevented from execution'
      - id: order_instructions
        type: order_instructions
        doc: 'Order Instructions'
      - id: reserved_32
        size: 32
        doc: 'Reserved for future use'
  unsequenced_data_packet:
    seq:
      - id: unsequenced_message_type
        type: str
        size: 2
        encoding: ASCII
        doc: 'SesM unsequenced message type'
      - id: unsequenced_message
        size: _parent.sesm_packet_header.sesm_packet_length - 2
        type:
          switch-on: unsequenced_message_type
          cases:
            '"N1"': new_order_request_message
            '"NR"': new_order_response_message
            '"M1"': modify_order_request_message
            '"MR"': modify_order_response
            '"CO"': cancel_order_request_message
            '"CR"': cancel_order_response
            '"XQ"': mass_cancel_request
            '"XR"': mass_cancel_response
            '"SD"': strategy_creation_request
            '"SR"': strategy_creation_response_message
  new_order_request_message:
    seq:
      - id: client_send_time
        type: nanosecond_timestamp
        doc: 'Firm’s send time. Nanoseconds since Unix epoch'
      - id: mp_id
        type: str
        size: 5
        encoding: ASCII
        pad-right: 0x20
        doc: 'Five character MPID of the Firm whose order is sent'
      - id: operator_id
        type: str
        size: 18
        encoding: ASCII
        doc: 'This must contain a 2 to 18 character Operator'
      - id: operator_location
        type: str
        size: 6
        encoding: ASCII
        doc: 'The location associated with Operator ID'
      - id: account
        type: str
        size: 16
        encoding: ASCII
        doc: 'Customer ID defined by the firm'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order ID'
      - id: instrument_id_binary_u_4
        type: u4
        doc: 'Instrument ID mapped to a given Instrument assigned by MIAX Futures Onyx'
      - id: price
        type: decimal_s8_9
        doc: 'Limit price of the order. Implied decimal with scale 1e-9'
      - id: stop_order_trigger_price
        type: decimal_s8_9
        doc: 'Stop Order Trigger Price, Ignored if not a stop order. Implied decimal with scale 1e-9'
      - id: size_binary_u_4
        type: u4
        doc: 'Number of contracts to buy/sell'
      - id: order_instructions
        type: order_instructions
        doc: 'Order Instructions'
      - id: time_in_force
        type: u1
        enum: time_in_force
        doc: 'Time in Force'
      - id: order_type
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Order Type'
      - id: self_trade_protection
        type: self_trade_protection
        doc: 'Self Trade Protection'
      - id: self_trade_protection_group
        type: str
        size: 2
        encoding: ASCII
        doc: 'Customer specified protection group, if empty string, group is not specified'
      - id: purge_group
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Customer specified purge group'
      - id: customer_order_handling_instruction
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Customer Order Handling Instruction:'
      - id: additional_order_indicators
        type: additional_order_indicators
        doc: 'Additional Order Indicators Flags'
      - id: min_qty
        type: u4
        doc: 'Minimum fill quantity'
      - id: order_expiry_date
        type: u2
        doc: 'GTD Order Expiry date, set to zero for all other tifs'
      - id: trading_collar_dollar_value
        type: decimal_s8_9
        doc: 'Custom Dollar Value Trading Collar Protection. Implied decimal with scale 1e-9'
      - id: cti_code
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'CTI Code values'
      - id: text_memo
        type: str
        size: 20
        encoding: ASCII
        doc: 'Clearing Text Memo'
      - id: reserved_32
        size: 32
        doc: 'Reserved for future use'
  modify_order_request_message:
    seq:
      - id: client_send_time
        type: nanosecond_timestamp
        doc: 'Firm’s send time. Nanoseconds since Unix epoch'
      - id: mp_id
        type: str
        size: 5
        encoding: ASCII
        pad-right: 0x20
        doc: 'Five character MPID of the Firm whose order is sent'
      - id: operator_id
        type: str
        size: 18
        encoding: ASCII
        doc: 'This must contain a 2 to 18 character Operator'
      - id: operator_location
        type: str
        size: 6
        encoding: ASCII
        doc: 'The location associated with Operator ID'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order ID'
      - id: original_client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Target Client Order ID that is being modified'
      - id: instrument_id_binary_u_4
        type: u4
        doc: 'Instrument ID mapped to a given Instrument assigned by MIAX Futures Onyx'
      - id: price
        type: decimal_s8_9
        doc: 'Limit price of the order. Implied decimal with scale 1e-9'
      - id: stop_order_trigger_price
        type: decimal_s8_9
        doc: 'Stop Order Trigger Price, Ignored if not a stop order. Implied decimal with scale 1e-9'
      - id: size_binary_s_4
        type: s4
        doc: 'New size of the order if size is being modified'
      - id: order_expiry_date
        type: u2
        doc: 'GTD Order Expiry date, set to zero for all other tifs'
      - id: self_trade_protection_group
        type: str
        size: 2
        encoding: ASCII
        doc: 'Customer specified protection group, if empty string, group is not specified'
      - id: purge_group
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Customer specified purge group'
      - id: customer_order_handling_instruction
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Customer Order Handling Instruction:'
      - id: additional_order_indicators
        type: additional_order_indicators
        doc: 'Additional Order Indicators Flags'
      - id: reserved_32
        size: 32
        doc: 'Reserved for future use'
  cancel_order_request_message:
    seq:
      - id: client_send_time
        type: nanosecond_timestamp
        doc: 'Firm’s send time. Nanoseconds since Unix epoch'
      - id: mp_id
        type: str
        size: 5
        encoding: ASCII
        pad-right: 0x20
        doc: 'Five character MPID of the Firm whose order is sent'
      - id: operator_id
        type: str
        size: 18
        encoding: ASCII
        doc: 'This must contain a 2 to 18 character Operator'
      - id: operator_location
        type: str
        size: 6
        encoding: ASCII
        doc: 'The location associated with Operator ID'
      - id: order_id
        type: u8
        doc: 'Exchange assigned unique order ID when order is'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order ID'
      - id: original_client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Target Client Order ID that is being modified'
      - id: instrument_id_binary_u_4
        type: u4
        doc: 'Instrument ID mapped to a given Instrument assigned by MIAX Futures Onyx'
      - id: reserved_10
        size: 10
        doc: 'Reserved for future use'
  mass_cancel_request:
    seq:
      - id: client_send_time
        type: nanosecond_timestamp
        doc: 'Firm’s send time. Nanoseconds since Unix epoch'
      - id: mp_id
        type: str
        size: 5
        encoding: ASCII
        pad-right: 0x20
        doc: 'Five character MPID of the Firm whose order is sent'
      - id: operator_id
        type: str
        size: 18
        encoding: ASCII
        doc: 'This must contain a 2 to 18 character Operator'
      - id: operator_location
        type: str
        size: 6
        encoding: ASCII
        doc: 'The location associated with Operator ID'
      - id: reserved_10
        size: 10
        doc: 'Reserved for future use'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order ID'
      - id: scope
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Mass-Cancel Scope:'
      - id: action
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Action to be taken for the specified Scope:'
      - id: product_group_code
        type: str
        size: 6
        encoding: ASCII
        doc: 'Product Group Code: e.g. MWE for Hard Red'
      - id: product_type
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Product Type:'
      - id: purge_group
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Customer specified purge group'
      - id: reserved_9
        size: 9
        doc: 'For future use'
  strategy_creation_request:
    seq:
      - id: client_send_time
        type: nanosecond_timestamp
        doc: 'Firm’s send time. Nanoseconds since Unix epoch'
      - id: mp_id
        type: str
        size: 5
        encoding: ASCII
        pad-right: 0x20
        doc: 'Five character MPID of the Firm whose order is sent'
      - id: operator_id
        type: str
        size: 18
        encoding: ASCII
        doc: 'This must contain a 2 to 18 character Operator'
      - id: operator_location
        type: str
        size: 6
        encoding: ASCII
        doc: 'The location associated with Operator ID'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order ID'
      - id: reserved_16
        size: 16
        doc: 'Reserved for future use'
      - id: num_strategy_leg
        type: u1
        doc: 'Number of strategy legs. The fields below'
      - id: strategy_leg
        type: strategy_leg
        repeat: expr
        repeat-expr: num_strategy_leg
        doc: 'Number of Legs'
  strategy_leg:
    seq:
      - id: instrument_id_binary_u_4
        type: u4
        doc: 'Instrument ID mapped to a given Instrument assigned by MIAX Futures Onyx'
      - id: leg_ratio
        type: s4
        doc: 'Leg ratio for the specified instrument'
      - id: reserved_8
        size: 8
        doc: 'Reserved for future use'
  login_request:
    seq:
      - id: sesm_version
        type: str
        size: 5
        encoding: ASCII
        pad-right: 0x20
      - id: username
        type: str
        size: 5
        encoding: ASCII
        pad-right: 0x20
        doc: 'issued by MIAX Futures Exchange during initial setup'
      - id: computer_id
        type: str
        size: 8
        encoding: ASCII
        pad-right: 0x20
        doc: 'issued by MIAX Futures Exchange during initial setup'
      - id: application_protocol
        type: str
        size: 8
        encoding: ASCII
        doc: 'Miax Application Protocol'
      - id: requested_session
        type: u1
        doc: 'Specifies the session the client would like to log into, or zero to log into the currently active session'
      - id: requested_sequence_number
        type: u8
        doc: 'Specifies client requested sequence number'
  login_response:
    seq:
      - id: login_status
        type: u1
        enum: login_status
        doc: 'Login Status'
      - id: session_id
        type: u1
        doc: 'MIAX Futures Onyx assigned ID for the current trading session for the Matching Engine'
      - id: highest_sequence_number
        type: u8
        doc: 'the highest sequence number that the server currently has for the client'
  retransmission_request:
    seq:
      - id: start_sequence_number
        type: u8
        doc: 'Sequence number of the first packet to be retransmitted'
      - id: end_sequence_number
        type: u8
        doc: 'Sequence number of the last packet to be retransmitted'
  logout_request:
    seq:
      - id: logout_reason
        type: u1
        enum: logout_reason
        doc: 'Logout Request Reason'
      - id: logout_text
        type: str
        size: _parent.sesm_packet_header.sesm_packet_length - 2
        encoding: ASCII
        doc: 'Free form human readable text'
  goodbye_packet:
    seq:
      - id: logout_reason
        type: u1
        enum: logout_reason
        doc: 'Logout Request Reason'
      - id: logout_text
        type: str
        size: _parent.sesm_packet_header.sesm_packet_length - 2
        encoding: ASCII
        doc: 'Free form human readable text'
  nanosecond_timestamp:
    seq:
      - id: time
        type: s8
    instances:
      hour:
        value: time / 3600000000000 % 24
      minute:
        value: time / 60000000000 % 60
      second:
        value: time / 1000000000 % 60
      millisecond:
        value: time / 1000000 % 1000
  decimal_s8_9:
    seq:
      - id: mantissa
        type: s8
    instances:
      real:
        value: mantissa / 1000000000.0

enums:
  sesm_packet_type:
    0x53:
      id: 'sequenced_data_packet'
      doc: 'SesM sequenced data packet'
    0x55:
      id: 'unsequenced_data_packet'
      doc: 'SesM unsequenced data packet'
    0x4c:
      id: 'login_request'
      doc: 'SesM Login Request'
    0x52:
      id: 'login_response'
      doc: 'SesM Login Response'
    0x43:
      id: 'synchronization_complete'
      doc: 'SesM Synchronization Complete'
    0x41:
      id: 'retransmission_request'
      doc: 'SesM Retransmission Request'
    0x58:
      id: 'logout_request'
      doc: 'SesM Logout Request'
    0x47:
      id: 'goodbye_packet'
      doc: 'SesM Logout Request'
    0x45:
      id: 'end_of_session'
      doc: 'SesM End of Session'
    0x30:
      id: 'server_heartbeat'
      doc: 'SesM Server Heartbeat'
    0x31:
      id: 'client_heartbeat'
      doc: 'SesM Client Heartbeat'
  time_in_force:
    0x49:
      id: 'ioc'
      doc: 'Immediate Or Cancel'
    0x44:
      id: 'day'
      doc: 'Day'
    0x46:
      id: 'fok'
      doc: 'Fill Or Kill'
    0x43:
      id: 'gtc'
      doc: 'Good Until Cancel'
    0x58:
      id: 'gtd'
      doc: 'Good Until Date'
  login_status:
    0x20:
      id: 'successful'
      doc: 'Successful'
    0x58:
      id: 'rejected'
      doc: 'Invalid Username/Computer ID combination'
    0x53:
      id: 'requested_session_is_not_available'
      doc: 'Requested session is not available'
    0x4e:
      id: 'invalid_start_sequence_number_requested'
      doc: 'Invalid start sequence number requested'
    0x49:
      id: 'incompatible_session_protocol_version'
      doc: 'Incompatible Session protocol version'
    0x41:
      id: 'incompatible_application_protocol_version'
      doc: 'Incompatible application protocol version'
    0x4c:
      id: 'request_rejected_because_client_already_logged_in'
      doc: 'Request rejected because client already logged in'
  logout_reason:
    0x20:
      id: 'graceful_logout'
      doc: 'Graceful Logout'
    0x42:
      id: 'bad_packet'
      doc: 'Bad SesM packet'
    0x4c:
      id: 'timed_out'
      doc: 'Timed out waiting for Login Packet'
    0x41:
      id: 'application_terminating_connection'
      doc: 'Application terminating connection'

