# ---------------------------------------------------------------------
# Kaitai struct definition for: Jpx FseEquities MarketByOrder Flex v1.1
#
# Protocol:
#   Organization: Japan Exchange Group
#   Protocol: Market By Order
#   Encoding: Flex
#   Version: 1.1
#   Date: 11/20/2024
#   Specification: TSEarrowhead_FLEX_MarketbyOrderSpecifications_ver.1.1.pdf
#
# Script:
#   Generator: 1.0.0.0
#   License: Public/GPLv3
#   Authors: Omi Developers
#
# Copyright (c) 2026 Scaled Sources LLC.  https://www.scaledsources.com
#
# This kaitai struct definition is contributed to The Open Markets Initiative under
# the license noted above.
#
# The protocol compiler technologies used to produce this file
# are the subject of patents owned by Scaled Sources LLC.  Those patent
# rights are retained and are not transferred by this contribution:
#   https://patents.google.com/patent/US20240129382A1/en
#   https://patents.google.com/patent/US20240419416A1/en
#
# Open Markets Initiative website:
#   https://openmarketsinitiative.com
# ---------------------------------------------------------------------

meta:
  id: jpx_fseequities_marketbyorder_flex_v1_1_udp
  title: Jpx FseEquities MarketByOrder Flex v1.1
  license: GPL-3.0
  endian: be

doc: 'Japan Exchange Group Fukuoka Stock Exchange Equities Market By Order Flex v1.1'

seq:
  - id: packet_header
    type: packet_header_struct
    doc: 'Jpx Flex 26 byte packet header'
  - id: message
    type: message_struct
    repeat: expr
    repeat-expr: packet_header.message_count
    doc: 'Jpx Flex tag wrapper'

types:
  packet_header_struct:
    seq:
      - id: multicast_group_number
        type: u1
        doc: 'Multicast Group Number for the request target'
      - id: number_of_system_reboots
        type: u1
        doc: 'For retransmission set to the number of times the system has been rebooted; for snapshot set to 0'
      - id: sequence_number
        type: u4
        doc: 'For retransmission set to the first sequence number for the request; for snapshot set to 0'
      - id: issue_code
        type: str
        size: 12
        encoding: ASCII
        pad-right: 0x20
        doc: 'Securities Identification Code left aligned with trailing spaces'
      - id: update_number
        type: u4
        doc: 'Per issue update number assigned from 1 each business day'
      - id: packet_number
        type: u1
        doc: 'Packet number within a multi packet split set always 0 in arrowhead4 0'
      - id: total_number_of_packets
        type: u1
        doc: 'Total packet count within a multi packet split set always 0 in arrowhead4 0'
      - id: utility_flag
        type: u1
        doc: 'Indicates whether another packet follows that was generated by the same transaction'
      - id: message_count
        type: u1
        doc: 'Number of tags in the packet'
  message_struct:
    seq:
      - id: message_header
        type: message_header
        doc: 'Jpx Flex tag header carrying length prefix and message type discriminator'
      - id: payload
        size: message_header.tag_length + 1 - 2
        type:
          switch-on: message_header.message_type
          cases:
            'message_type::seconds_timestamp_message': seconds_timestamp_message
            'message_type::trading_status_message': trading_status_message
            'message_type::execution_summary_message': execution_summary_message
            'message_type::add_order_message': add_order_message
            'message_type::order_executed_message': order_executed_message
            'message_type::order_executed_with_price_message': order_executed_with_price_message
            'message_type::order_delete_message': order_delete_message
            'message_type::reset_message': reset_message
            'message_type::communication_control_message': communication_control_message
  message_header:
    seq:
      - id: tag_length
        type: u1
        doc: 'Length in bytes of the Tag Data including the Message Type byte'
      - id: message_type
        type: u1
        enum: message_type
        doc: 'First byte of the tag identifying the message type used as dispatch key'
  seconds_timestamp_message:
    seq:
      - id: time_seconds
        type: second_timestamp
        doc: 'Set to UNIX time (seconds since 1970-01-01 00:00:00 UTC). Seconds since Unix epoch'
  trading_status_message:
    seq:
      - id: time_microseconds
        type: microsecond_offset
        doc: 'Time to the nearest microsecond. Microseconds since Second epoch'
      - id: market_status
        type: u1
        enum: market_status
        doc: 'Indicates market status'
      - id: status_flag
        type: str
        size: 2
        encoding: ASCII
        doc: 'Indicates trading status'
      - id: short_selling_status
        type: u1
        enum: short_selling_status
        doc: 'Indicates application of the Short Selling Regulation'
      - id: pricing_method
        type: u1
        enum: pricing_method
        doc: 'Indicates method of pricing or status of quote display after the tag is delivered'
      - id: book_center_price
        type: decimal_u8_4
        doc: 'Set to the book center price while the Itayose method is in place or while a quote is displayed. Implied decimal with scale 1e-4'
  execution_summary_message:
    seq:
      - id: time_microseconds
        type: microsecond_offset
        doc: 'Time to the nearest microsecond. Microseconds since Second epoch'
      - id: triggered_side
        type: u1
        enum: triggered_side
        doc: 'Indicates the side whose order triggered the execution'
      - id: total_volume
        size: 6
        doc: 'Total volume of executed orders in number of shares'
      - id: total_invalidation
        size: 6
        doc: 'Total volume of invalidated orders in number of shares'
      - id: last_price
        type: decimal_u8_4
        doc: 'Last price at the time the execution was processed. Implied decimal with scale 1e-4'
      - id: match_id
        type: u4
        doc: 'Identifier assigned per issue on an execution basis, unique and sequential each business day'
      - id: best_offer
        type: decimal_u8_4_nullable
        doc: 'Best offer at the time the execution processing finishes; set to 0 at market close. Implied decimal with scale 1e-4. Nullable, No Best Offer = 0'
      - id: best_bid
        type: decimal_u8_4_nullable
        doc: 'Best bid at the time the execution processing finishes; set to 0 at market close. Implied decimal with scale 1e-4. Nullable, No Best Bid = 0'
  add_order_message:
    seq:
      - id: time_microseconds
        type: microsecond_offset
        doc: 'Time to the nearest microsecond. Microseconds since Second epoch'
      - id: order_id
        type: u4
        doc: 'Identifier assigned per issue on an order basis, unique and sequential each business day'
      - id: side
        type: u1
        enum: side
        doc: 'Indicates buy or sell'
      - id: quantity
        size: 6
        doc: 'Order quantity registered on the order book in number of shares'
      - id: price
        type: decimal_u8_4_nullable
        doc: 'Price registered on the order book; for market orders set to the maximum 64-bit value. Implied decimal with scale 1e-4. Nullable, Market Order = 18446744073709551615'
      - id: order_condition
        type: u1
        enum: order_condition
        doc: 'Indicates the order condition'
      - id: modification_flag
        type: u1
        enum: modification_flag
        doc: 'When the A tag is generated by a modification order, indicates whether there is a change of time priority'
  order_executed_message:
    seq:
      - id: time_microseconds
        type: microsecond_offset
        doc: 'Time to the nearest microsecond. Microseconds since Second epoch'
      - id: order_id
        type: u4
        doc: 'Identifier assigned per issue on an order basis, unique and sequential each business day'
      - id: side
        type: u1
        enum: side
        doc: 'Indicates buy or sell'
      - id: volume
        size: 6
        doc: 'Executed volume in number of shares'
      - id: match_id
        type: u4
        doc: 'Identifier assigned per issue on an execution basis, unique and sequential each business day'
  order_executed_with_price_message:
    seq:
      - id: time_microseconds
        type: microsecond_offset
        doc: 'Time to the nearest microsecond. Microseconds since Second epoch'
      - id: order_id
        type: u4
        doc: 'Identifier assigned per issue on an order basis, unique and sequential each business day'
      - id: side
        type: u1
        enum: side
        doc: 'Indicates buy or sell'
      - id: volume
        size: 6
        doc: 'Executed volume in number of shares'
      - id: match_id
        type: u4
        doc: 'Identifier assigned per issue on an execution basis, unique and sequential each business day'
      - id: execution_price
        type: decimal_u8_4
        doc: 'Execution price. Implied decimal with scale 1e-4'
      - id: adopted_pricing_method
        type: u1
        enum: adopted_pricing_method
        doc: 'Indicates the pricing method in place when the execution occurred'
  order_delete_message:
    seq:
      - id: time_microseconds
        type: microsecond_offset
        doc: 'Time to the nearest microsecond. Microseconds since Second epoch'
      - id: order_id
        type: u4
        doc: 'Identifier assigned per issue on an order basis, unique and sequential each business day'
      - id: side
        type: u1
        enum: side
        doc: 'Indicates buy or sell'
      - id: modification_flag
        type: u1
        enum: modification_flag
        doc: 'When the A tag is generated by a modification order, indicates whether there is a change of time priority'
  reset_message:
    seq:
      - id: reset_start_end_flag
        type: u1
        enum: reset_start_end_flag
        doc: 'When TSE needs to reset all distributed data, this indicates the start or end of the process'
  communication_control_message:
    seq:
      - id: test_mode_flag
        type: u1
        enum: test_mode_flag
        doc: 'Indicates production or test'
      - id: communication_start_end_flag
        type: u1
        enum: communication_start_end_flag
        doc: 'Indicates the start or end of communication'
  second_timestamp:
    seq:
      - id: time
        type: s4
    instances:
      hour:
        value: time / 3600 % 24
      minute:
        value: time / 60 % 60
      second:
        value: time % 60
  microsecond_offset:
    seq:
      - id: time
        type: s4
    instances:
      millisecond:
        value: time / 1000 % 1000
      microsecond:
        value: time % 1000
  decimal_u8_4:
    seq:
      - id: mantissa
        type: u8
    instances:
      real:
        value: mantissa / 10000.0
  decimal_u8_4_nullable:
    seq:
      - id: value
        type: decimal_u8_4
    instances:
      is_null:
        value: value.mantissa == 0

enums:
  message_type:
    0x54:
      id: 'seconds_timestamp_message'
      doc: 'Provides information about the time of processing on the Trading Server to the nearest second. Always delivered at the time the information is generated, except for Reset and Communication Control. Only one tag is delivered per process and stored at the top of the first packet.'
    0x4f:
      id: 'trading_status_message'
      doc: 'Provides information about the status of trading on a per-issue basis. Delivered when there is a change in the tag.'
    0x4b:
      id: 'execution_summary_message'
      doc: 'Provides summary information about execution. Delivered when an execution occurs.'
    0x41:
      id: 'add_order_message'
      doc: 'Provides information about book registration. Delivered when a new order or modification order is registered.'
    0x45:
      id: 'order_executed_message'
      doc: 'Provides information about registered orders in case of Zaraba execution. Delivered when an execution occurs in Zaraba.'
    0x43:
      id: 'order_executed_with_price_message'
      doc: 'Provides information about registered orders in case of Itayose execution. Delivered when an execution occurs by the Itayose method or while an SQ or STQ is displayed.'
    0x44:
      id: 'order_delete_message'
      doc: 'Provides information about order deletion from the order book. Delivered when an order is deleted via a cancel order or a modification order or when a registered order expires.'
    0x52:
      id: 'reset_message'
      doc: 'A tag requesting the resetting (i.e. cancellation) of all distributed information. When the user receives this tag, the user must clear all valid A tags.'
    0x4c:
      id: 'communication_control_message'
      doc: 'Provides information about communication control. Delivered when communication starts and ends, and in between at minute intervals.'
  market_status:
    11:
      id: 'morning_session_order_acceptance_time'
      doc: 'Morning Session Order Acceptance Time'
    12:
      id: 'morning_session_trading_hours'
      doc: 'Morning Session Trading Hours'
    19:
      id: 'end_of_morning_session'
      doc: 'End Of Morning Session'
    21:
      id: 'afternoon_session_order_acceptance_time'
      doc: 'Afternoon Session Order Acceptance Time'
    22:
      id: 'afternoon_session_trading_hours'
      doc: 'Afternoon Session Trading Hours'
    23:
      id: 'afternoon_session_preclosing'
      doc: 'Afternoon Session Preclosing'
    29:
      id: 'end_of_afternoon_session'
      doc: 'End Of Afternoon Session'
  short_selling_status:
    0:
      id: 'short_selling_regulation_is_not_applied'
      doc: 'Short Selling Regulation Is Not Applied'
    1:
      id: 'short_selling_regulation_is_applied'
      doc: 'Short Selling Regulation Is Applied'
  pricing_method:
    1:
      id: 'itayose_method'
      doc: 'Itayose Method'
    2:
      id: 'zaraba_method'
      doc: 'Zaraba Method'
    3:
      id: 'sell_special_quote_displayed'
      doc: 'Sell Special Quote Displayed'
    4:
      id: 'buy_special_quote_displayed'
      doc: 'Buy Special Quote Displayed'
    5:
      id: 'sell_sequential_trade_quote_displayed'
      doc: 'Sell Sequential Trade Quote Displayed'
    6:
      id: 'buy_sequential_trade_quote_displayed'
      doc: 'Buy Sequential Trade Quote Displayed'
    0:
      id: 'other_than_the_above'
      doc: 'Other Than The Above'
  triggered_side:
    0x53:
      id: 'sell_order'
      doc: 'Sell Order'
    0x42:
      id: 'buy_order'
      doc: 'Buy Order'
    0x20:
      id: 'itayose_execution'
      doc: 'Itayose Execution'
  side:
    0x53:
      id: 'sell_order'
      doc: 'Sell Order'
    0x42:
      id: 'buy_order'
      doc: 'Buy Order'
  order_condition:
    0:
      id: 'nonconditional'
      doc: 'Nonconditional'
    2:
      id: 'onopen'
      doc: 'Onopen'
    4:
      id: 'onclose'
      doc: 'Onclose'
    6:
      id: 'funari'
      doc: 'Funari'
  modification_flag:
    0:
      id: 'cancel_order_or_modification_order_that_changes_time_priority'
      doc: 'Cancel Order Or Modification Order That Changes Time Priority'
    1:
      id: 'modification_order_that_does_not_change_time_priority'
      doc: 'Modification Order That Does Not Change Time Priority'
  adopted_pricing_method:
    1:
      id: 'itayose_method'
      doc: 'Itayose Method'
    2:
      id: 'quote_displayed'
      doc: 'Quote Displayed'
  reset_start_end_flag:
    1:
      id: 'start_of_reset_dissemination'
      doc: 'Start Of Reset Dissemination'
    2:
      id: 'end_of_reset_dissemination'
      doc: 'End Of Reset Dissemination'
  test_mode_flag:
    1:
      id: 'production'
      doc: 'Production'
    2:
      id: 'test'
      doc: 'Test'
  communication_start_end_flag:
    0:
      id: 'health_check_control'
      doc: 'Health Check Control'
    1:
      id: 'communication_start'
      doc: 'Communication Start'
    2:
      id: 'communication_end'
      doc: 'Communication End'
  packet_type:
    0x52:
      id: 'login_request_message'
      doc: 'Tcp login request for retransmission or snapshot. Packet Type R selects retransmission and L selects snapshot.'
    0x41:
      id: 'login_result_message'
      doc: 'Tcp login response. Packet Type A indicates accepted and J indicates rejected.'
    0x53:
      id: 'message_response_message'
      doc: 'Tcp message response carrying tag data including their packet headers in response to a retransmission or snapshot request.'
    0x47:
      id: 'end_of_message_message'
      doc: 'Tcp end of message marker terminating a retransmission or snapshot session.'
  result_code:
    0x41:
      id: 'accepted'
      doc: 'Accepted'
    0x4f:
      id: 'out_of_service'
      doc: 'Out Of Service'
    0x55:
      id: 'incorrect_user_id'
      doc: 'Incorrect User Id'
    0x53:
      id: 'incorrect_sequence_number'
      doc: 'Incorrect Sequence Number'
    0x54:
      id: 'incorrect_packet_type'
      doc: 'Incorrect Packet Type'
    0x4d:
      id: 'incorrect_mcg_number'
      doc: 'Incorrect Mcg Number'
    0x5a:
      id: 'other_error'
      doc: 'Other Error'

