# ---------------------------------------------------------------------
# Kaitai struct definition for: Miax PearlEquities ExpressOrders Meo v2.6
#
# Protocol:
#   Organization: Miami International Holdings
#   Protocol: Express Orders
#   Encoding: Miax Express Orders
#   Version: 2.6
#   Date: 9/25/2023
#   Specification: miax_express_orders_meo.pdf
#
# Script:
#   Generator: 1.0.0.0
#   License: Public/GPLv3
#   Authors: Omi Developers
#
# Copyright (c) 2026 Scaled Sources LLC.  https://www.scaledsources.com
#
# This kaitai struct definition is contributed to The Open Markets Initiative under
# the license noted above.
#
# The protocol compiler technologies used to produce this file
# are the subject of patents owned by Scaled Sources LLC.  Those patent
# rights are retained and are not transferred by this contribution:
#   https://patents.google.com/patent/US20240129382A1/en
#   https://patents.google.com/patent/US20240419416A1/en
#
# Open Markets Initiative website:
#   https://openmarketsinitiative.com
# ---------------------------------------------------------------------

meta:
  id: miax_pearlequities_expressorders_meo_v2_6
  title: Miax PearlEquities ExpressOrders Meo v2.6
  license: GPL-3.0
  endian: le

doc: 'Miami International Holdings MIAX Pearl Equities Express Orders Meo v2.6'
doc-ref: https://www.miaxglobal.com/markets/us-equities/pearl-equities/interface-specifications

seq:
  - id: esesm_tcp_packet
    type: esesm_tcp_packet_struct
    repeat: eos
    doc: 'ESesM Tcp Packet'

types:
  esesm_tcp_packet_struct:
    seq:
      - id: esesm_packet_header
        type: esesm_packet_header
        doc: 'ESesM packet header'
      - id: esesm_payload
        size: esesm_packet_header.esesm_packet_length + 2 - 3
        type:
          switch-on: esesm_packet_header.esesm_packet_type
          cases:
            'esesm_packet_type::sequenced_data_packet': sequenced_data_packet
            'esesm_packet_type::unsequenced_data_packet': unsequenced_data_packet
            'esesm_packet_type::login_request': login_request
            'esesm_packet_type::login_response': login_response
            'esesm_packet_type::synchronization_complete': synchronization_complete
            'esesm_packet_type::retransmission_request': retransmission_request
            'esesm_packet_type::logout_request': logout_request
            'esesm_packet_type::goodbye_packet': goodbye_packet
            'esesm_packet_type::test_packet': test_packet
  esesm_packet_header:
    seq:
      - id: esesm_packet_length
        type: u2
        doc: 'The length of rest of the packet'
      - id: esesm_packet_type
        type: u1
        enum: esesm_packet_type
        doc: 'ESesM protocol packet type'
  sequenced_data_packet:
    seq:
      - id: sequence_number
        type: u8
        doc: 'Sequence number of this sequenced data packet'
      - id: matching_engine_id
        type: u1
        doc: 'Matching Engine that originated the packet'
      - id: sequenced_message_type
        type: str
        size: 2
        encoding: ASCII
        doc: 'ESesM sequenced message type'
      - id: sequenced_message
        size: _parent.esesm_packet_header.esesm_packet_length - 12 - 11
        type:
          switch-on: sequenced_message_type
          cases:
            '"SU"': symbol_update
            '"NR"': new_order_response_message
            '"MR"': modify_order_response
            '"CR"': cancel_order_response
            '"CQ"': cancel_order_by_exchange_order_id_response_message
            '"SN"': system_state_notification
            '"O1"': new_order_notification
            '"MN"': modify_order_notification
            '"XN"': cancel_reduce_size_order_notification
            '"PU"': order_price_update_notification
            '"RA"': reserve_order_replenishment_notification
            '"E1"': execution_notification
  symbol_update:
    seq:
      - id: matching_engine_time
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the Matching Engine. Nanoseconds since Unix epoch'
      - id: symbol_id
        type: u4
        doc: 'Symbol ID mapped to a given symbol'
      - id: ticker_symbol
        type: str
        size: 11
        encoding: ASCII
        pad-right: 0x20
        doc: 'Ticker symbol for the security in NASDAQ'
      - id: reserved_1
        size: 1
        doc: 'Reserved for future use'
      - id: test_security_indicator
        type: u1
        enum: test_security_indicator
        doc: 'Test Security Indicator'
      - id: future
        type: u1
        doc: 'Reserved for future use'
      - id: lot_size
        type: u4
        doc: 'Round Lot size in shares'
      - id: opening_time
        type: str
        size: 8
        encoding: ASCII
        pad-right: 0x20
        doc: 'Expressed in HH:MM:SS format Eg:'
      - id: closing_time
        type: str
        size: 8
        encoding: ASCII
        pad-right: 0x20
        doc: 'Expressed in HH:MM:SS format Eg:'
      - id: primary_market_code
        type: u1
        enum: primary_market_code
        doc: 'Primary Market Code'
      - id: reserved_12
        size: 12
        doc: 'Reserved for future use'
  new_order_response_message:
    seq:
      - id: matching_engine_time
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the Matching Engine. Nanoseconds since Unix epoch'
      - id: mpid
        type: str
        size: 4
        encoding: ASCII
        pad-right: 0x20
        doc: 'Four character NSCC MPID of the Firm'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order Id'
      - id: symbol_id
        type: u4
        doc: 'Symbol ID mapped to a given symbol'
      - id: order_id
        type: u8
        doc: 'Exchanged assigned unique order ID when order is accepted'
      - id: price
        type: decimal_u8_6
        doc: 'Limit price of the order. Implied decimal with scale 1e-6'
      - id: size
        type: u4
        doc: 'Number of shares to buy/sell'
      - id: order_status
        type: u1
        enum: order_status
        doc: 'Order Status'
      - id: reserved_19
        size: 19
        doc: 'Reserved for future use'
  modify_order_response:
    seq:
      - id: matching_engine_time
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the Matching Engine. Nanoseconds since Unix epoch'
      - id: mpid
        type: str
        size: 4
        encoding: ASCII
        pad-right: 0x20
        doc: 'Four character NSCC MPID of the Firm'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order Id'
      - id: original_client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Target Client Order ID that is being modified'
      - id: symbol_id
        type: u4
        doc: 'Symbol ID mapped to a given symbol'
      - id: order_id
        type: u8
        doc: 'Exchanged assigned unique order ID when order is accepted'
      - id: leaves_qty
        type: u4
        doc: 'Size of the order that is still open, includes size on'
      - id: price
        type: decimal_u8_6
        doc: 'Limit price of the order. Implied decimal with scale 1e-6'
      - id: modify_status
        type: u1
        enum: modify_status
        doc: 'Modify Status'
      - id: reserved_10
        size: 10
        doc: 'Reserved for future use'
  cancel_order_response:
    seq:
      - id: matching_engine_time
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the Matching Engine. Nanoseconds since Unix epoch'
      - id: mpid
        type: str
        size: 4
        encoding: ASCII
        pad-right: 0x20
        doc: 'Four character NSCC MPID of the Firm'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order Id'
      - id: original_client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Target Client Order ID that is being modified'
      - id: symbol_id
        type: u4
        doc: 'Symbol ID mapped to a given symbol'
      - id: order_id
        type: u8
        doc: 'Exchanged assigned unique order ID when order is accepted'
      - id: leaves_qty
        type: u4
        doc: 'Size of the order that is still open, includes size on'
      - id: cancel_status
        type: u1
        enum: cancel_status
        doc: 'Cancel Status'
      - id: reserved_10
        size: 10
        doc: 'Reserved for future use'
  cancel_order_by_exchange_order_id_response_message:
    seq:
      - id: matching_engine_time
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the Matching Engine. Nanoseconds since Unix epoch'
      - id: mpid
        type: str
        size: 4
        encoding: ASCII
        pad-right: 0x20
        doc: 'Four character NSCC MPID of the Firm'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order Id'
      - id: symbol_id
        type: u4
        doc: 'Symbol ID mapped to a given symbol'
      - id: order_id
        type: u8
        doc: 'Exchanged assigned unique order ID when order is accepted'
      - id: leaves_qty
        type: u4
        doc: 'Size of the order that is still open, includes size on'
      - id: cancel_status
        type: u1
        enum: cancel_status
        doc: 'Cancel Status'
      - id: reserved_10
        size: 10
        doc: 'Reserved for future use'
  system_state_notification:
    seq:
      - id: matching_engine_time
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the Matching Engine. Nanoseconds since Unix epoch'
      - id: meo_version
        type: str
        size: 8
        encoding: ASCII
        pad-right: 0x20
        doc: 'MEO interface version Eg: MEO1 0'
      - id: session_id
        type: u1
        doc: 'MIAX Pearl Equities assigned ID for the current'
      - id: system_status
        type: u1
        enum: system_status
        doc: 'System Status'
      - id: reserved_8
        size: 8
        doc: 'Reserved for future use'
  new_order_notification:
    seq:
      - id: matching_engine_time
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the Matching Engine. Nanoseconds since Unix epoch'
      - id: mpid
        type: str
        size: 4
        encoding: ASCII
        pad-right: 0x20
        doc: 'Four character NSCC MPID of the Firm'
      - id: order_id
        type: u8
        doc: 'Exchanged assigned unique order ID when order is accepted'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order Id'
      - id: symbol_id
        type: u4
        doc: 'Symbol ID mapped to a given symbol'
      - id: price
        type: decimal_u8_6
        doc: 'Limit price of the order. Implied decimal with scale 1e-6'
      - id: size
        type: u4
        doc: 'Number of shares to buy/sell'
      - id: new_order_instructions
        type: new_order_instructions
        doc: 'New Order Instructions'
      - id: time_in_force
        type: u1
        enum: time_in_force
        doc: 'Time in Force'
      - id: order_type
        type: u1
        enum: order_type
        doc: 'Order Type'
      - id: price_sliding_and_reprice_frequency
        type: u1
        enum: price_sliding_and_reprice_frequency
        doc: 'Price Sliding and Reprice Frequency'
      - id: self_trade_protection
        type: self_trade_protection
        doc: 'Self Trade Protection'
      - id: self_trade_protection_group
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Customer specified protection group'
      - id: routing
        type: routing
        doc: 'Routing Flags'
      - id: trading_collar_dollar_value
        type: decimal_s8_6
        doc: 'Market Order Custom Dollar Value Trading Collar Protection. Implied decimal with scale 1e-6'
      - id: capacity
        type: u1
        enum: capacity
        doc: 'Capacity'
      - id: account
        type: str
        size: 16
        encoding: ASCII
        doc: 'Optional customer ID provided by the Firm'
      - id: clearing_account
        type: str
        size: 4
        encoding: ASCII
        doc: 'Optional supplemental order identifier'
      - id: min_qty
        type: u4
        doc: 'Minimum fill quantity'
      - id: max_floor_qty
        type: u4
        doc: 'Number of shares of the order to display'
      - id: display_range_qty
        type: u4
        doc: 'Used for random replenishment of Reserve orders'
      - id: peg_offset
        type: decimal_s8_6
        doc: 'Signed dollar value up to four decimal places for a pegged order. Implied decimal with scale 1e-6'
      - id: locate_account
        type: str
        size: 4
        encoding: ASCII
        doc: 'Optional information provided by Firm for Sell'
      - id: purge_group
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Customer specified purge group'
      - id: original_order_capacity
        type: u1
        enum: original_order_capacity
        doc: 'As specified in the New Order Request'
      - id: reserved_18
        size: 18
        doc: 'Reserved for future use'
  new_order_instructions:
    meta:
      bit-endian: le
    seq:
      - id: side
        type: b1
        doc: 'Side'
      - id: short_sale_indicator
        type: b2
        doc: 'Short Sale Indicator'
      - id: displayed
        type: b1
        doc: 'Displayed'
      - id: post_only
        type: b1
        doc: 'PostOnly'
      - id: locate_required
        type: b1
        doc: 'Locate Required'
      - id: iso
        type: b1
        doc: 'ISO'
      - id: retail_order
        type: b1
        doc: 'Retail Order'
      - id: attributable_order
        type: b2
        doc: 'Attributable Order'
      - id: min_qty_exec_type
        type: b2
        doc: 'Attributable Order'
      - id: cancel_order_if_not_a_nbbo_setter
        type: b1
        doc: 'Cancel Order if NOT a NBBO Setter'
      - id: unused_3
        type: b3
        doc: 'Reserved for future use'
  self_trade_protection:
    meta:
      bit-endian: le
    seq:
      - id: self_trade_protection_level
        type: b3
        doc: 'Self Trade Protection Level'
      - id: self_trade_protection_instruction
        type: b3
        doc: 'Self Trade Protection Instruction'
      - id: unused_2
        type: b2
        doc: 'Reserved for future use'
  routing:
    meta:
      bit-endian: le
    seq:
      - id: routing_instruction
        type: b3
        doc: 'Routing Instruction'
      - id: routing_strategy
        type: b3
        doc: 'Routing Strategy'
      - id: unused_2
        type: b2
        doc: 'Reserved for future use'
  modify_order_notification:
    seq:
      - id: matching_engine_time
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the Matching Engine. Nanoseconds since Unix epoch'
      - id: mpid
        type: str
        size: 4
        encoding: ASCII
        pad-right: 0x20
        doc: 'Four character NSCC MPID of the Firm'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order Id'
      - id: original_client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Target Client Order ID that is being modified'
      - id: symbol_id
        type: u4
        doc: 'Symbol ID mapped to a given symbol'
      - id: order_id
        type: u8
        doc: 'Exchanged assigned unique order ID when order is accepted'
      - id: price
        type: decimal_u8_6
        doc: 'Limit price of the order. Implied decimal with scale 1e-6'
      - id: size
        type: u4
        doc: 'Number of shares to buy/sell'
      - id: leaves_qty
        type: u4
        doc: 'Size of the order that is still open, includes size on'
      - id: modify_order_instructions
        type: modify_order_instructions
        doc: 'Modify Order Instructions'
      - id: min_qty
        type: u4
        doc: 'Minimum fill quantity'
      - id: max_floor_qty
        type: u4
        doc: 'Number of shares of the order to display'
      - id: pending_modify_status
        type: u1
        enum: pending_modify_status
        doc: 'Modification request status'
      - id: pending_reject_reason
        type: u1
        enum: pending_reject_reason
        doc: 'Pending replace reject reason'
      - id: locate_account
        type: str
        size: 4
        encoding: ASCII
        doc: 'Optional information provided by Firm for Sell'
      - id: reserved_26
        size: 26
        doc: 'Reserved for future use'
  modify_order_instructions:
    meta:
      bit-endian: le
    seq:
      - id: short_sale_indicator
        type: b2
        doc: 'Short Sale Indicator'
      - id: locate_required
        type: b1
        doc: 'Locate Required'
      - id: unused_5
        type: b5
        doc: 'Reserved for future use'
  cancel_reduce_size_order_notification:
    seq:
      - id: matching_engine_time
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the Matching Engine. Nanoseconds since Unix epoch'
      - id: mpid
        type: str
        size: 4
        encoding: ASCII
        pad-right: 0x20
        doc: 'Four character NSCC MPID of the Firm'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order Id'
      - id: symbol_id
        type: u4
        doc: 'Symbol ID mapped to a given symbol'
      - id: order_id
        type: u8
        doc: 'Exchanged assigned unique order ID when order is accepted'
      - id: leaves_qty
        type: u4
        doc: 'Size of the order that is still open, includes size on'
      - id: cancel_reason
        type: u1
        enum: cancel_reason
        doc: 'Cancel Reason'
      - id: last_price
        type: decimal_u8_6
        doc: 'Match price if the order had not been prevented. Implied decimal with scale 1e-6'
      - id: last_size
        type: u4
        doc: 'Number of shares that would have matched if the'
      - id: pending_cancel_status
        type: u1
        enum: pending_cancel_status
        doc: 'Status for Pending Cancel Request'
      - id: pending_reject_reason
        type: u1
        enum: pending_reject_reason
        doc: 'Pending replace reject reason'
      - id: reserved_8
        size: 8
        doc: 'Reserved for future use'
  order_price_update_notification:
    seq:
      - id: matching_engine_time
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the Matching Engine. Nanoseconds since Unix epoch'
      - id: symbol_id
        type: u4
        doc: 'Symbol ID mapped to a given symbol'
      - id: order_id
        type: u8
        doc: 'Exchanged assigned unique order ID when order is accepted'
      - id: working_price
        type: decimal_u8_6
        doc: 'Current Working Price of the order. Implied decimal with scale 1e-6'
      - id: nbbo_indicator
        type: u1
        enum: nbbo_indicator
        doc: 'NBBO Indicator'
      - id: reserved_9
        size: 9
        doc: 'Reserved for future use'
  reserve_order_replenishment_notification:
    seq:
      - id: matching_engine_time
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the Matching Engine. Nanoseconds since Unix epoch'
      - id: symbol_id
        type: u4
        doc: 'Symbol ID mapped to a given symbol'
      - id: order_id
        type: u8
        doc: 'Exchanged assigned unique order ID when order is accepted'
      - id: secondary_order_id
        type: u8
        doc: 'Secondary Order ID used to publish the display'
      - id: display_qty
        type: u4
        doc: 'Display size of the Reserve order after replenishment'
      - id: reserved_10
        size: 10
        doc: 'Reserved for future use'
  execution_notification:
    seq:
      - id: matching_engine_time
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the Matching Engine. Nanoseconds since Unix epoch'
      - id: mpid
        type: str
        size: 4
        encoding: ASCII
        pad-right: 0x20
        doc: 'Four character NSCC MPID of the Firm'
      - id: symbol_id
        type: u4
        doc: 'Symbol ID mapped to a given symbol'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order Id'
      - id: trade_id
        type: u8
        doc: 'Exchange assigned unique Trade ID See notes'
      - id: execution_id
        type: u8
        doc: 'Exchange assigned unique Execution ID See notes'
      - id: correction_number
        type: u1
        doc: 'Trade correction number'
      - id: trade_status
        type: u1
        enum: trade_status
        doc: 'Possible values:'
      - id: last_price
        type: decimal_u8_6
        doc: 'Match price if the order had not been prevented. Implied decimal with scale 1e-6'
      - id: last_size
        type: u4
        doc: 'Number of shares that would have matched if the'
      - id: order_execution_instructions
        type: order_execution_instructions
        doc: 'Order Exucution Instructions'
      - id: executing_trading_center
        type: u1
        enum: executing_trading_center
        doc: 'Exchange at which trade was executed'
      - id: secondary_order_id
        type: u8
        doc: 'Secondary Order ID used to publish the display'
      - id: liquidity_indicator
        type: str
        size: 3
        encoding: ASCII
        doc: 'Please refer to MIAX Pearl Equities Liquidity Indicator'
      - id: locate_account
        type: str
        size: 4
        encoding: ASCII
        doc: 'Optional information provided by Firm for Sell'
      - id: original_order_capacity
        type: u1
        enum: original_order_capacity
        doc: 'As specified in the New Order Request'
      - id: additional_liquidity_indicator
        type: additional_liquidity_indicator
        doc: 'Additional liquidity flags'
      - id: executing_trading_center_mpid
        type: str
        size: 4
        encoding: ASCII
        doc: 'Reserved for future use'
      - id: reserved_12
        size: 12
        doc: 'Reserved for future use'
  order_execution_instructions:
    meta:
      bit-endian: le
    seq:
      - id: side
        type: b1
        doc: 'Side'
      - id: unused_15
        type: b15
        doc: 'Reserved for future use'
  additional_liquidity_indicator:
    meta:
      bit-endian: le
    seq:
      - id: nbbo_setter_joiner
        type: b3
        doc: 'NBBO Setter/Joiner/First Joiner'
      - id: unused_5
        type: b5
        doc: 'Reserved for future use'
  unsequenced_data_packet:
    seq:
      - id: unsequenced_message_type
        type: str
        size: 2
        encoding: ASCII
        doc: 'ESesM unsequenced message type'
      - id: unsequenced_message
        size: _parent.esesm_packet_header.esesm_packet_length - 3 - 2
        type:
          switch-on: unsequenced_message_type
          cases:
            '"N1"': new_order_request_message
            '"NR"': new_order_response_message
            '"M1"': modify_order_request_message
            '"MR"': modify_order_response
            '"CO"': cancel_order_request
            '"CR"': cancel_order_response
            '"CX"': cancel_order_by_exchange_order_id_request
            '"CQ"': cancel_order_by_exchange_order_id_response_message
            '"XQ"': mass_cancel_request
            '"XR"': mass_cancel_response
            '"RA"': reserve_order_replenishment_notification
            '"E1"': execution_notification
  new_order_request_message:
    seq:
      - id: reserved_8
        size: 8
        doc: 'Reserved for future use'
      - id: mpid
        type: str
        size: 4
        encoding: ASCII
        pad-right: 0x20
        doc: 'Four character NSCC MPID of the Firm'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order Id'
      - id: symbol_id
        type: u4
        doc: 'Symbol ID mapped to a given symbol'
      - id: price
        type: decimal_u8_6
        doc: 'Limit price of the order. Implied decimal with scale 1e-6'
      - id: size
        type: u4
        doc: 'Number of shares to buy/sell'
      - id: new_order_instructions
        type: new_order_instructions
        doc: 'New Order Instructions'
      - id: time_in_force
        type: u1
        enum: time_in_force
        doc: 'Time in Force'
      - id: order_type
        type: u1
        enum: order_type
        doc: 'Order Type'
      - id: price_sliding_and_reprice_frequency
        type: u1
        enum: price_sliding_and_reprice_frequency
        doc: 'Price Sliding and Reprice Frequency'
      - id: self_trade_protection
        type: self_trade_protection
        doc: 'Self Trade Protection'
      - id: self_trade_protection_group
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Customer specified protection group'
      - id: routing
        type: routing
        doc: 'Routing Flags'
      - id: trading_collar_dollar_value
        type: decimal_s8_6
        doc: 'Market Order Custom Dollar Value Trading Collar Protection. Implied decimal with scale 1e-6'
      - id: capacity
        type: u1
        enum: capacity
        doc: 'Capacity'
      - id: account
        type: str
        size: 16
        encoding: ASCII
        doc: 'Optional customer ID provided by the Firm'
      - id: clearing_account
        type: str
        size: 4
        encoding: ASCII
        doc: 'Optional supplemental order identifier'
      - id: min_qty
        type: u4
        doc: 'Minimum fill quantity'
      - id: max_floor_qty
        type: u4
        doc: 'Number of shares of the order to display'
      - id: display_range_qty
        type: u4
        doc: 'Used for random replenishment of Reserve orders'
      - id: peg_offset
        type: decimal_s8_6
        doc: 'Signed dollar value up to four decimal places for a pegged order. Implied decimal with scale 1e-6'
      - id: locate_account
        type: str
        size: 4
        encoding: ASCII
        doc: 'Optional information provided by Firm for Sell'
      - id: purge_group
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Customer specified purge group'
      - id: reserved_19
        size: 19
        doc: 'Reserved for future use'
  modify_order_request_message:
    seq:
      - id: reserved_8
        size: 8
        doc: 'Reserved for future use'
      - id: mpid
        type: str
        size: 4
        encoding: ASCII
        pad-right: 0x20
        doc: 'Four character NSCC MPID of the Firm'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order Id'
      - id: original_client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Target Client Order ID that is being modified'
      - id: symbol_id
        type: u4
        doc: 'Symbol ID mapped to a given symbol'
      - id: price
        type: decimal_u8_6
        doc: 'Limit price of the order. Implied decimal with scale 1e-6'
      - id: size
        type: u4
        doc: 'Number of shares to buy/sell'
      - id: modify_order_instructions
        type: modify_order_instructions
        doc: 'Modify Order Instructions'
      - id: min_qty
        type: u4
        doc: 'Minimum fill quantity'
      - id: max_floor_qty
        type: u4
        doc: 'Number of shares of the order to display'
      - id: locate_account
        type: str
        size: 4
        encoding: ASCII
        doc: 'Optional information provided by Firm for Sell'
      - id: reserved_28
        size: 28
        doc: 'Reserved for future use'
  cancel_order_request:
    seq:
      - id: reserved_8
        size: 8
        doc: 'Reserved for future use'
      - id: mpid
        type: str
        size: 4
        encoding: ASCII
        pad-right: 0x20
        doc: 'Four character NSCC MPID of the Firm'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order Id'
      - id: original_client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Target Client Order ID that is being modified'
      - id: symbol_id
        type: u4
        doc: 'Symbol ID mapped to a given symbol'
      - id: reserved_10
        size: 10
        doc: 'Reserved for future use'
  cancel_order_by_exchange_order_id_request:
    seq:
      - id: reserved_8
        size: 8
        doc: 'Reserved for future use'
      - id: mpid
        type: str
        size: 4
        encoding: ASCII
        pad-right: 0x20
        doc: 'Four character NSCC MPID of the Firm'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order Id'
      - id: order_id
        type: u8
        doc: 'Exchanged assigned unique order ID when order is accepted'
      - id: symbol_id
        type: u4
        doc: 'Symbol ID mapped to a given symbol'
      - id: reserved_10
        size: 10
        doc: 'Reserved for future use'
  mass_cancel_request:
    seq:
      - id: reserved_8
        size: 8
        doc: 'Reserved for future use'
      - id: mpid
        type: str
        size: 4
        encoding: ASCII
        pad-right: 0x20
        doc: 'Four character NSCC MPID of the Firm'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order Id'
      - id: scope
        type: u1
        enum: scope
        doc: 'Scope'
      - id: action
        type: u1
        enum: action
        doc: '‘B’ – Block only The system will reject all new'
      - id: purge_group
        type: str
        size: 1
        encoding: ASCII
        pad-right: 0x20
        doc: 'Customer specified purge group'
      - id: reserved_9
        size: 9
        doc: 'Reserved for future use'
  mass_cancel_response:
    seq:
      - id: notification_time
        type: nanosecond_timestamp
        doc: 'Time at which this message was generated by the. Nanoseconds since Unix epoch'
      - id: mpid
        type: str
        size: 4
        encoding: ASCII
        pad-right: 0x20
        doc: 'Four character NSCC MPID of the Firm'
      - id: client_order_id
        type: str
        size: 20
        encoding: ASCII
        doc: 'Firm specified unique order Id'
      - id: number_of_matching_engines
        type: u1
        doc: '24 This is the number of Matching Engines in'
      - id: matching_engine_status
        type: str
        size: 24
        encoding: ASCII
        pad-right: 0x20
        doc: 'Status response for the Mass Cancel Request from'
      - id: reserved_10
        size: 10
        doc: 'Reserved for future use'
  login_request:
    seq:
      - id: esesm_version
        type: str
        size: 5
        encoding: ASCII
        pad-right: 0x20
        doc: 'Protocol version'
      - id: username
        type: str
        size: 5
        encoding: ASCII
        pad-right: 0x20
        doc: 'issued by MIAX during initial setup'
      - id: computer_id
        type: str
        size: 8
        encoding: ASCII
        pad-right: 0x20
        doc: 'issued by MIAX Futures Exchange during initial setup'
      - id: application_protocol
        type: str
        size: 8
        encoding: ASCII
        pad-right: 0x20
        doc: 'Miax Application Protocol'
      - id: requested_trading_session_id
        type: u1
        doc: 'Specifies the session the client would like to log into, or zero to log into the currently active session'
      - id: requested_sequence_number
        type: u8
        doc: 'Specifies client requested sequence number'
  login_response:
    seq:
      - id: number_of_matching_engines
        type: u1
        doc: '24 This is the number of Matching Engines in'
      - id: login_status
        type: u1
        enum: login_status
        doc: 'Login Status'
      - id: trading_session_id
        type: u1
        doc: 'The current trading session ID of the corresponding Matching Engine'
      - id: highest_sequence_number
        type: u8
        doc: 'the highest sequence number that the server currently has for the client'
  synchronization_complete:
    seq:
      - id: number_of_matching_engines
        type: u1
        doc: '24 This is the number of Matching Engines in'
  retransmission_request:
    seq:
      - id: start_sequence_number
        type: u8
        doc: 'Sequence number of the first packet to be retransmitted'
      - id: end_sequence_number
        type: u8
        doc: 'Sequence number of the last packet to be retransmitted'
  logout_request:
    seq:
      - id: logout_reason
        type: u1
        enum: logout_reason
        doc: 'Logout Request Reason'
      - id: logout_text
        type: str
        size: _parent.esesm_packet_header.esesm_packet_length - 2
        encoding: ASCII
        doc: 'Free form human readable text'
  goodbye_packet:
    seq:
      - id: logout_reason
        type: u1
        enum: logout_reason
        doc: 'Logout Request Reason'
      - id: logout_text
        type: str
        size: _parent.esesm_packet_header.esesm_packet_length - 2
        encoding: ASCII
        doc: 'Free form human readable text'
  test_packet:
    seq:
      - id: test_text
        type: str
        size: _parent.esesm_packet_header.esesm_packet_length - 1
        encoding: ASCII
        doc: 'Free form human readable text'
  nanosecond_timestamp:
    seq:
      - id: time
        type: s8
    instances:
      hour:
        value: time / 3600000000000 % 24
      minute:
        value: time / 60000000000 % 60
      second:
        value: time / 1000000000 % 60
      millisecond:
        value: time / 1000000 % 1000
  decimal_u8_6:
    seq:
      - id: mantissa
        type: u8
    instances:
      real:
        value: mantissa / 1000000.0
  decimal_s8_6:
    seq:
      - id: mantissa
        type: s8
    instances:
      real:
        value: mantissa / 1000000.0

enums:
  esesm_packet_type:
    0x73:
      id: 'sequenced_data_packet'
      doc: 'ESesM sequenced data packet'
    0x55:
      id: 'unsequenced_data_packet'
      doc: 'ESesM unsequenced data packet'
    0x6c:
      id: 'login_request'
      doc: 'ESesM Login Request'
    0x72:
      id: 'login_response'
      doc: 'ESesM Login Response'
    0x63:
      id: 'synchronization_complete'
      doc: 'ESesM Synchronization Complete'
    0x61:
      id: 'retransmission_request'
      doc: 'ESesM Retransmission Request'
    0x58:
      id: 'logout_request'
      doc: 'ESesM Logout Request'
    0x47:
      id: 'goodbye_packet'
      doc: 'ESesM Logout Request'
    0x75:
      id: 'trading_session_update'
      doc: 'ESesM Trading Session Update'
    0x30:
      id: 'server_heartbeat'
      doc: 'ESesM Server Heartbeat'
    0x31:
      id: 'client_heartbeat'
      doc: 'ESesM Client Heartbeat'
    0x54:
      id: 'test_packet'
      doc: 'ESesM Test Packet'
  test_security_indicator:
    0x59:
      id: 'yes_field'
      doc: 'Yes'
    0x4e:
      id: 'no_field'
      doc: 'No'
  primary_market_code:
    0x41:
      id: 'nyse_american'
      doc: 'Nyse American'
    0x42:
      id: 'nasdaq_bx'
      doc: 'Nasdaq Bx'
    0x43:
      id: 'nyse_national'
      doc: 'Nyse National'
    0x48:
      id: 'miax_pearl_equities'
      doc: 'Miax Pearl Equities'
    0x49:
      id: 'nasdaq_ise'
      doc: 'Nasdaq Ise'
    0x4a:
      id: 'cboe_edga_exchange'
      doc: 'Cboe Edga Exchange'
    0x4b:
      id: 'cboe_edgx_exchange'
      doc: 'Cboe Edgx Exchange'
    0x4c:
      id: 'long_term_stock_exchange'
      doc: 'Long Term Stock Exchange'
    0x4d:
      id: 'nyse_chicago'
      doc: 'Nyse Chicago'
    0x4e:
      id: 'new_york_stock_exchange'
      doc: 'New York Stock Exchange'
    0x50:
      id: 'nyse_arca'
      doc: 'Nyse Arca'
    0x51:
      id: 'nasdaq'
      doc: 'Nasdaq'
    0x55:
      id: 'members_exchange'
      doc: 'Members Exchange'
    0x56:
      id: 'investors_exchange'
      doc: 'Investors Exchange'
    0x58:
      id: 'nasdaq_phlx'
      doc: 'Nasdaq Phlx'
    0x59:
      id: 'cboe_byx_exchange'
      doc: 'Cboe Byx Exchange'
    0x5a:
      id: 'cboe_bzx_exchange'
      doc: 'Cboe Bzx Exchange'
  order_status:
    0x41:
      id: 'duplicate_client_order_id'
      doc: 'Duplicate Client Order Id'
    0x42:
      id: 'not_in_live_order_window'
      doc: 'Not In Live Order Window'
    0x43:
      id: 'matching_engine_is_not_available'
      doc: 'Matching Engine Is Not Available'
    0x44:
      id: 'duplicate_order_check_rejected'
      doc: 'Duplicate Order Check Rejected'
    0x45:
      id: 'exceeded_test_symbol_throttle'
      doc: 'Exceeded Test Symbol Throttle'
    0x46:
      id: 'iso_orders_not_allowed'
      doc: 'Iso Orders Not Allowed'
    0x47:
      id: 'invalid_self_trade_protection_group_or_its_use'
      doc: 'Invalid Self Trade Protection Group Or Its Use'
    0x48:
      id: 'blocked_by_meo_user'
      doc: 'Blocked By Meo User'
    0x49:
      id: 'invalid_mpid'
      doc: 'Invalid Mpid'
    0x4a:
      id: 'invalid_price'
      doc: 'Invalid Price'
    0x4b:
      id: 'invalid_size'
      doc: 'Invalid Size'
    0x4c:
      id: 'blocked_by_firm_over_miax_member_firm'
      doc: 'Blocked By Firm Over Miax Member Firm'
    0x4d:
      id: 'exceeded_max_allowed_size'
      doc: 'Exceeded Max Allowed Size'
    0x4e:
      id: 'exceeded_max_notional_value'
      doc: 'Exceeded Max Notional Value'
    0x4f:
      id: 'invalid_client_order_id'
      doc: 'Invalid Client Order Id'
    0x50:
      id: 'request_is_not_permitted_for_this_session'
      doc: 'Request Is Not Permitted For This Session'
    0x51:
      id: 'short_sale_orders_not_allowed'
      doc: 'Short Sale Orders Not Allowed'
    0x52:
      id: 'blocked_by_cumulative_risk_metrics'
      doc: 'Blocked By Cumulative Risk Metrics'
    0x53:
      id: 'invalid_symbol_id'
      doc: 'Invalid Symbol Id'
    0x54:
      id: 'invalid_order_type'
      doc: 'Invalid Order Type'
    0x55:
      id: 'invalid_use_of_locate_required'
      doc: 'Invalid Use Of Locate Required'
    0x56:
      id: 'invalid_sell_short'
      doc: 'Invalid Sell Short'
    0x57:
      id: 'limit_order_price_protection'
      doc: 'Limit Order Price Protection'
    0x58:
      id: 'mpid_not_permitted'
      doc: 'Mpid Not Permitted'
    0x59:
      id: 'iso_attribute_not_compatible_with_the_order_type'
      doc: 'Iso Attribute Not Compatible With The Order Type'
    0x5a:
      id: 'undefined_reason'
      doc: 'Undefined Reason'
    0x61:
      id: 'invalid_capacity'
      doc: 'Invalid Capacity'
    0x62:
      id: 'invalid_time_in_force'
      doc: 'Invalid Time In Force'
    0x63:
      id: 'invalid_routing_instruction_or_use'
      doc: 'Invalid Routing Instruction Or Use'
    0x64:
      id: 'invalid_self_trade_protection_level'
      doc: 'Invalid Self Trade Protection Level'
    0x65:
      id: 'invalid_self_trade_protection_instruction_or_use'
      doc: 'Invalid Self Trade Protection Instruction Or Use'
    0x66:
      id: 'invalid_attributable_value_or_use'
      doc: 'Invalid Attributable Value Or Use'
    0x67:
      id: 'invalid_price_sliding_and_reprice_frequency_value_or_use'
      doc: 'Invalid Price Sliding And Reprice Frequency Value Or Use'
    0x68:
      id: 'invalid_use_of_post_only_instruction'
      doc: 'Invalid Use Of Post Only Instruction'
    0x69:
      id: 'invalid_use_of_display_instruction'
      doc: 'Invalid Use Of Display Instruction'
    0x6a:
      id: 'invalid_value_or_use_for_available_when_locked'
      doc: 'Invalid Value Or Use For Available When Locked'
    0x6b:
      id: 'market_order_price_protection'
      doc: 'Market Order Price Protection'
    0x6c:
      id: 'invalid_routing_strategy_or_its_use'
      doc: 'Invalid Routing Strategy Or Its Use'
    0x6d:
      id: 'invalid_value_in_account'
      doc: 'Invalid Value In Account'
    0x6e:
      id: 'invalid_value_in_clearing_account'
      doc: 'Invalid Value In Clearing Account'
    0x6f:
      id: 'invalid_use_of_trading_collar_dollar_value'
      doc: 'Invalid Use Of Trading Collar Dollar Value'
    0x70:
      id: 'invalid_for_current_symbol_trading_status'
      doc: 'Invalid For Current Symbol Trading Status'
    0x71:
      id: 'primary_exchange_ipo_not_complete_ipo_in_progress'
      doc: 'Primary Exchange Ipo Not Complete Ipo In Progress'
    0x72:
      id: 'invalid_use_of_min_qty_size_or_min_qty_exec_type_instruction'
      doc: 'Invalid Use Of Min Qty Size Or Min Qty Exec Type Instruction'
    0x73:
      id: 'invalid_use_of_order_type'
      doc: 'Invalid Use Of Order Type'
    0x74:
      id: 'invalid_max_floor_qty'
      doc: 'Invalid Max Floor Qty'
    0x75:
      id: 'invalid_display_range_qty'
      doc: 'Invalid Display Range Qty'
    0x76:
      id: 'feature_not_available'
      doc: 'Feature Not Available'
    0x77:
      id: 'primary_listing_market_routing_not_supported'
      doc: 'Primary Listing Market Routing Not Supported'
    0x78:
      id: 'too_late_for_primary_listing_market_order'
      doc: 'Too Late For Primary Listing Market Order'
    0x79:
      id: 'pac_orders_are_not_allowed_routing_to_primary'
      doc: 'Pac Orders Are Not Allowed Routing To Primary'
    0x7a:
      id: 'short_sale_exempt_orders_not_allowed'
      doc: 'Short Sale Exempt Orders Not Allowed'
    0x30:
      id: 'limit_price_more_aggressive_than_market_impact_collar'
      doc: 'Limit Price More Aggressive Than Market Impact Collar'
    0x31:
      id: 'market_orders_not_allowed'
      doc: 'Market Orders Not Allowed'
    0x32:
      id: 'restricted_security_not_allowed'
      doc: 'Restricted Security Not Allowed'
    0x33:
      id: 'blocked_by_order_rate_metrics'
      doc: 'Blocked By Order Rate Metrics'
    0x34:
      id: 'average_daily_volume_protection'
      doc: 'Average Daily Volume Protection'
    0x35:
      id: 'invalid_offset_for_primary_peg_order'
      doc: 'Invalid Offset For Primary Peg Order'
    0x36:
      id: 'invalid_purge_group_specified'
      doc: 'Invalid Purge Group Specified'
    0x37:
      id: 'invalid_or_not_permitted_value_in_locate_account'
      doc: 'Invalid Or Not Permitted Value In Locate Account'
    0x38:
      id: 'blocked_by_drop_copy_acod_event'
      doc: 'Blocked By Drop Copy Acod Event'
    0x39:
      id: 'blocked_by_drop_copy_acosf_event'
      doc: 'Blocked By Drop Copy Acosf Event'
    0x21:
      id: 'invalid_use_of_cancel_order_if_not_a_nbbo_setter'
      doc: 'Invalid Use Of Cancel Order If Not A Nbbo Setter'
    0x2a:
      id: 'downgraded_from_older_version'
      doc: 'Downgraded From Older Version'
  modify_status:
    0x20:
      id: 'successful'
      doc: 'Successful'
    0x41:
      id: 'duplicate_client_order_id'
      doc: 'Duplicate Client Order Id'
    0x42:
      id: 'not_in_live_order_window'
      doc: 'Not In Live Order Window'
    0x43:
      id: 'matching_engine_is_not_available'
      doc: 'Matching Engine Is Not Available'
    0x44:
      id: 'cannot_find_order_with_target_client_order_id'
      doc: 'Cannot Find Order With Target Client Order Id'
    0x45:
      id: 'exceeded_test_symbol_throttle'
      doc: 'Exceeded Test Symbol Throttle'
    0x46:
      id: 'order_is_routed'
      doc: 'Order Is Routed'
    0x47:
      id: 'short_sale_orders_not_allowed'
      doc: 'Short Sale Orders Not Allowed'
    0x48:
      id: 'blocked_by_meo_user'
      doc: 'Blocked By Meo User'
    0x49:
      id: 'invalid_mpid'
      doc: 'Invalid Mpid'
    0x4a:
      id: 'invalid_price'
      doc: 'Invalid Price'
    0x4b:
      id: 'invalid_size'
      doc: 'Invalid Size'
    0x4c:
      id: 'blocked_by_firm_over_miax_member_firm_portal_or_by_helpdesk'
      doc: 'Blocked By Firm Over Miax Member Firm Portal Or By Helpdesk'
    0x4d:
      id: 'exceeded_max_allowed_size'
      doc: 'Exceeded Max Allowed Size'
    0x4e:
      id: 'exceeded_max_notional_value'
      doc: 'Exceeded Max Notional Value'
    0x4f:
      id: 'invalid_client_order_id'
      doc: 'Invalid Client Order Id'
    0x50:
      id: 'request_is_not_permitted_for_this_session'
      doc: 'Request Is Not Permitted For This Session'
    0x51:
      id: 'specified_mpid_does_not_match_target_order'
      doc: 'Specified Mpid Does Not Match Target Order'
    0x52:
      id: 'blocked_by_cumulative_risk_metrics'
      doc: 'Blocked By Cumulative Risk Metrics'
    0x53:
      id: 'invalid_symbol_id'
      doc: 'Invalid Symbol Id'
    0x54:
      id: 'invalid_target_client_order_id'
      doc: 'Invalid Target Client Order Id'
    0x55:
      id: 'invalid_use_of_locate_required'
      doc: 'Invalid Use Of Locate Required'
    0x56:
      id: 'invalid_sell_short'
      doc: 'Invalid Sell Short'
    0x57:
      id: 'limit_order_price_protection'
      doc: 'Limit Order Price Protection'
    0x58:
      id: 'mpid_not_permitted'
      doc: 'Mpid Not Permitted'
    0x5a:
      id: 'undefined_reason'
      doc: 'Undefined Reason'
    0x61:
      id: 'invalid_min_qty_modification'
      doc: 'Invalid Min Qty Modification'
    0x62:
      id: 'invalid_to_change_max_floor_qty'
      doc: 'Invalid To Change Max Floor Qty'
    0x63:
      id: 'modification_request_is_sent_to_another_market_and_pending_completion'
      doc: 'Modification Request Is Sent To Another Market And Pending Completion'
    0x64:
      id: 'not_allowed_order_is_already_pending_modification'
      doc: 'Not Allowed Order Is Already Pending Modification'
    0x74:
      id: 'invalid_max_floor_qty'
      doc: 'Invalid Max Floor Qty'
    0x79:
      id: 'pac_orders_are_not_allowed_routing_to_primary'
      doc: 'Pac Orders Are Not Allowed Routing To Primary'
    0x7a:
      id: 'short_sale_exempt_orders_not_allowed'
      doc: 'Short Sale Exempt Orders Not Allowed'
    0x30:
      id: 'limit_price_more_aggressive_than_market_impact'
      doc: 'Limit Price More Aggressive Than Market Impact'
    0x31:
      id: 'market_orders_not_allowed'
      doc: 'Market Orders Not Allowed'
    0x32:
      id: 'restricted_security_not_allowed'
      doc: 'Restricted Security Not Allowed'
    0x33:
      id: 'blocked_by_order_rate_metrics'
      doc: 'Blocked By Order Rate Metrics'
    0x34:
      id: 'average_daily_volume_protection'
      doc: 'Average Daily Volume Protection'
    0x37:
      id: 'invalid_or_not_permitted_value_in_locate_account_field'
      doc: 'Invalid Or Not Permitted Value In Locate Account Field'
    0x38:
      id: 'blocked_by_drop_copy_acod_event'
      doc: 'Blocked By Drop Copy Acod Event'
    0x39:
      id: 'blocked_by_drop_copy_acosf_event'
      doc: 'Blocked By Drop Copy Acosf Event'
    0x2a:
      id: 'downgraded_from_older_version'
      doc: 'Downgraded From Older Version'
  cancel_status:
    0x20:
      id: 'successful'
      doc: 'Successful'
    0x41:
      id: 'duplicate_client_order_id'
      doc: 'Duplicate Client Order Id'
    0x42:
      id: 'not_in_live_order_window'
      doc: 'Not In Live Order Window'
    0x43:
      id: 'matching_engine_is_not_available'
      doc: 'Matching Engine Is Not Available'
    0x44:
      id: 'cannot_find_order_with_target_client_order_id'
      doc: 'Cannot Find Order With Target Client Order Id'
    0x45:
      id: 'exceeded_test_symbol_throttle'
      doc: 'Exceeded Test Symbol Throttle'
    0x46:
      id: 'order_is_routed'
      doc: 'Order Is Routed'
    0x49:
      id: 'invalid_mpid'
      doc: 'Invalid Mpid'
    0x4f:
      id: 'invalid_client_order_id'
      doc: 'Invalid Client Order Id'
    0x50:
      id: 'request_is_not_permitted_for_this_session'
      doc: 'Request Is Not Permitted For This Session'
    0x51:
      id: 'specified_mpid_does_not_match_target_order'
      doc: 'Specified Mpid Does Not Match Target Order'
    0x53:
      id: 'invalid_symbol_id'
      doc: 'Invalid Symbol Id'
    0x54:
      id: 'invalid_target_client_order_id'
      doc: 'Invalid Target Client Order Id'
    0x58:
      id: 'mpid_not_permitted'
      doc: 'Mpid Not Permitted'
    0x5a:
      id: 'undefined_reason'
      doc: 'Undefined Reason'
    0x63:
      id: 'modification_request_is_sent_to_another_market_and_pending_completion'
      doc: 'Modification Request Is Sent To Another Market And Pending Completion'
    0x2a:
      id: 'downgraded_from_older_version'
      doc: 'Downgraded From Older Version'
  system_status:
    0x53:
      id: 'start_of_system_hours'
      doc: 'Start Of System Hours'
    0x43:
      id: 'end_of_system_hours'
      doc: 'End Of System Hours'
    0x31:
      id: 'start_of_test_session'
      doc: 'Start Of Test Session'
    0x32:
      id: 'end_of_test_session'
      doc: 'End Of Test Session'
  side:
    0:
      id: 'buy'
      doc: 'Buy'
    1:
      id: 'sell'
      doc: 'Sell'
  short_sale_indicator:
    0:
      id: 'not_applicable'
      doc: 'Not Applicable'
    1:
      id: 'sell_long'
      doc: 'Sell Long'
    2:
      id: 'sell_short'
      doc: 'Sell Short'
    3:
      id: 'sell_short_exempt'
      doc: 'Sell Short Exempt'
  displayed:
    0:
      id: 'no_field'
      doc: 'No'
    1:
      id: 'yes_field'
      doc: 'Yes'
  post_only:
    0:
      id: 'no_field'
      doc: 'No'
    1:
      id: 'yes_field'
      doc: 'Yes'
  locate_required:
    0:
      id: 'not_applicable'
      doc: 'Not Applicable'
    1:
      id: 'yes_field'
      doc: 'Yes'
  iso:
    0:
      id: 'no_field'
      doc: 'No'
    1:
      id: 'yes_field'
      doc: 'Yes'
  retail_order:
    0:
      id: 'no_field'
      doc: 'No'
    1:
      id: 'yes_field'
      doc: 'Yes'
  attributable_order:
    0:
      id: 'no_field'
      doc: 'No'
    1:
      id: 'attributed_to_firm_mpid'
      doc: 'Attributed To Firm Mpid'
    2:
      id: 'attributed_rtal_to_this_order'
      doc: 'Attributed Rtal To This Order'
  min_qty_exec_type:
    0:
      id: 'not_applicable'
      doc: 'Not Applicable'
    1:
      id: 'single_contra_order'
      doc: 'Only Single Contra Order Can Fulfill Min Qty Requirement'
    2:
      id: 'multiple_contra_orders'
      doc: 'Only Single Contra Order Can Fulfill Min Qty Requirement'
  cancel_order_if_not_a_nbbo_setter:
    0:
      id: 'no_field'
      doc: 'No'
    1:
      id: 'yes_field'
      doc: 'Yes'
  time_in_force:
    0x52:
      id: 'regular_hours_only'
      doc: 'Regular Hours Only'
    0x49:
      id: 'immediate_or_cancel'
      doc: 'Immediate Or Cancel'
  order_type:
    0x31:
      id: 'limit'
      doc: 'Limit'
    0x32:
      id: 'market'
      doc: 'Market'
    0x4d:
      id: 'midpoint_peg'
      doc: 'Midpoint Peg'
    0x6d:
      id: 'midpoint_peg_but_do_not_match_when_nbbo_is_locked'
      doc: 'Midpoint Peg But Do Not Match When Nbbo Is Locked'
    0x52:
      id: 'primary_peg'
      doc: 'Primary Peg'
    0x72:
      id: 'primary_peg_but_do_not_match_when_nbbo_is_locked'
      doc: 'Primary Peg But Do Not Match When Nbbo Is Locked'
  price_sliding_and_reprice_frequency:
    0x44:
      id: 'reprice_once'
      doc: 'Reprice Once'
    0x43:
      id: 'reprice_once_but_cancel_if_crossed_at_entry'
      doc: 'Reprice Once But Cancel If Crossed At Entry'
    0x4d:
      id: 'reprice_multiple_times'
      doc: 'Reprice Multiple Times'
    0x4e:
      id: 'no_price_sliding'
      doc: 'No Price Sliding'
    0x51:
      id: 'not_applicable'
      doc: 'Not Applicable'
  self_trade_protection_level:
    0:
      id: 'self_trade_protection_disabled'
      doc: 'Self Trade Protection Disabled'
    1:
      id: 'firm'
      doc: 'Firm'
    2:
      id: 'mpid'
      doc: 'Mpid'
    3:
      id: 'parent_group'
      doc: 'Parent Group'
  self_trade_protection_instruction:
    0:
      id: 'not_applicable'
      doc: 'Not Applicable'
    1:
      id: 'cancel_newest'
      doc: 'Cancel Newest'
    2:
      id: 'cancel_oldest'
      doc: 'Cancel Oldest'
    3:
      id: 'cancel_both'
      doc: 'Cancel Both'
    4:
      id: 'decrement_and_cancel'
      doc: 'Decrement And Cancel'
  routing_instruction:
    0:
      id: 'route_once'
      doc: 'Route Once'
    1:
      id: 'reroutable'
      doc: 'Reroutable'
    2:
      id: 'do_not_route'
      doc: 'Do Not Route'
  routing_strategy:
    0:
      id: 'not_applicable'
      doc: 'Not Applicable'
    1:
      id: 'order_protection'
      doc: 'Order Protection'
    2:
      id: 'primary_auction'
      doc: 'Primary Auction'
  capacity:
    0x41:
      id: 'agency'
      doc: 'Agency'
    0x50:
      id: 'principal'
      doc: 'Principal'
    0x52:
      id: 'riskless_principal'
      doc: 'Riskless Principal'
  original_order_capacity:
    0x41:
      id: 'agency'
      doc: 'Agency'
    0x50:
      id: 'principal'
      doc: 'Principal'
    0x52:
      id: 'riskless_principal'
      doc: 'Riskless Principal'
  pending_modify_status:
    0x20:
      id: 'pending_modification_is_completed_or'
      doc: 'Pending Modification Is Completed Or'
    0x50:
      id: 'modification_request_is_sent_to_another'
      doc: 'Modification Request Is Sent To Another'
    0x58:
      id: 'pending_modification_request_is_rejected'
      doc: 'Pending Modification Request Is Rejected'
  pending_reject_reason:
    0x20:
      id: 'not_applicable'
      doc: 'Not Applicable'
    0x58:
      id: 'rejected_by_primary_listing_market'
      doc: 'Rejected By Primary Listing Market'
  cancel_reason:
    0x41:
      id: 'cancelled_due_to_cumulative_risk_metrics'
      doc: 'Cancelled Due To Cumulative Risk Metrics'
    0x42:
      id: 'reserved_for_future_use'
      doc: 'Reserved For Future Use'
    0x43:
      id: 'time_in_force_cancelled'
      doc: 'Time In Force Cancelled'
    0x44:
      id: 'auto_cancel_on_disconnect_acod'
      doc: 'Auto Cancel On Disconnect Acod'
    0x45:
      id: 'post_only_order_is_lockingcrossing_miax'
      doc: 'Post Only Order Is Lockingcrossing Miax'
    0x46:
      id: 'auto_cancel_on_system_failure_acosf'
      doc: 'Auto Cancel On System Failure Acosf'
    0x47:
      id: 'cancelled_due_to_price_sliding_instruction'
      doc: 'Cancelled Due To Price Sliding Instruction'
    0x48:
      id: 'cancelled_by_helpdesk_or_over_miax_member'
      doc: 'Cancelled By Helpdesk Or Over Miax Member'
    0x49:
      id: 'order_expired'
      doc: 'Order Expired'
    0x4a:
      id: 'symbol_trading_status_makes_pac_market'
      doc: 'Symbol Trading Status Makes Pac Market'
    0x4b:
      id: 'trading_collar_protection'
      doc: 'Trading Collar Protection'
    0x4c:
      id: 'sell_short_iso_when_short_sale_price_test_is'
      doc: 'Sell Short Iso When Short Sale Price Test Is'
    0x4d:
      id: 'symbol_is_not_trading'
      doc: 'Symbol Is Not Trading'
    0x4e:
      id: 'limit_order_price_protection'
      doc: 'Limit Order Price Protection'
    0x4f:
      id: 'route_to_primary_listing_market_rejected'
      doc: 'Route To Primary Listing Market Rejected'
    0x50:
      id: 'cancelled_by_a_mass_cancel_request_over_a_priority_purge_port'
      doc: 'Cancelled By A Mass Cancel Request Over A Priority Purge Port'
    0x51:
      id: 'unexpected_cancel_by_primary_listing_market'
      doc: 'Unexpected Cancel By Primary Listing Market'
    0x52:
      id: 'cancelled_due_to_failed_price_improvement'
      doc: 'Cancelled Due To Failed Price Improvement'
    0x53:
      id: 'cancelled_due_to_primary_auction_route'
      doc: 'Cancelled Due To Primary Auction Route'
    0x54:
      id: 'cancelled_due_to_order_rate_protection'
      doc: 'Cancelled Due To Order Rate Protection'
    0x55:
      id: 'cancelled_by_user_through_order_entry_session'
      doc: 'Cancelled By User Through Order Entry Session'
    0x56:
      id: 'invalid_pegged_order_price'
      doc: 'Invalid Pegged Order Price'
    0x57:
      id: 'pac_order_cancelled_as_security_is_halted'
      doc: 'Pac Order Cancelled As Security Is Halted'
    0x58:
      id: 'not_applicable_used_when_pending_cancel'
      doc: 'Not Applicable Used When Pending Cancel'
    0x59:
      id: 'primary_auction_order_is_cancelled_due_to_a'
      doc: 'Primary Auction Order Is Cancelled Due To A'
    0x30:
      id: 'cancelled_due_to_market_impact_collar'
      doc: 'Cancelled Due To Market Impact Collar'
    0x31:
      id: 'cancel_newest_instruction'
      doc: 'Full Cancel Due To Self Trade Protection'
    0x32:
      id: 'cancel_oldest_instruction'
      doc: 'Full Cancel Due To Self Trade Protection'
    0x33:
      id: 'cancel_both_instruction'
      doc: 'Full Cancel Due To Self Trade Protection'
    0x34:
      id: 'decrement_and_cancel_instruction'
      doc: 'Full Partial Cancel Due To Self Trade Protection'
    0x35:
      id: 'cancelled_due_to_drop_copy_acod_event'
      doc: 'Cancelled Due To Drop Copy Acod Event'
    0x36:
      id: 'cancelled_due_to_drop_copy_acosf_event'
      doc: 'Cancelled Due To Drop Copy Acosf Event'
    0x37:
      id: 'cancelled_as_order_did_not_set_nbbo'
      doc: 'Cancelled As Order Did Not Set Nbbo'
    0x38:
      id: 'cancelled_by_user_through_a_session_other'
      doc: 'Cancelled By User Through A Session Other'
    0x5a:
      id: 'undefined_reason'
      doc: 'Undefined Reason'
    0x2a:
      id: 'downgraded_from_older_version'
      doc: 'Downgraded From Older Version'
  pending_cancel_status:
    0x20:
      id: 'completed_or_not_applicable'
      doc: 'Pending Cancellation Is Completed Or Pending State Is Not Applicable'
    0x58:
      id: 'pending_cancellation_request_is_rejected'
      doc: 'Pending Cancellation Request Is Rejected'
    0x50:
      id: 'cancel_request_was_received_but_is_pending'
      doc: 'Cancel Request Was Received But Is Pending'
  nbbo_indicator:
    0x59:
      id: 'order_set_new_nbbo'
      doc: 'Order Set New Nbbo'
    0x46:
      id: 'first_order_to_set_mbbo_equal_to_nbbo'
      doc: 'First Order To Set Mbbo Equal To Nbbo'
    0x4e:
      id: 'not_applicable'
      doc: 'Not Applicable'
  trade_status:
    0x45:
      id: 'new_execution'
      doc: 'New Execution'
    0x43:
      id: 'price_size_correction'
      doc: 'Price Size Correction'
    0x58:
      id: 'trade_cancellation'
      doc: 'Trade Cancellation'
  executing_trading_center:
    0x41:
      id: 'nyse_american'
      doc: 'Nyse American'
    0x42:
      id: 'nasdaq_bx'
      doc: 'Nasdaq Bx'
    0x43:
      id: 'nyse_national'
      doc: 'Nyse National'
    0x48:
      id: 'miax_pearl_equities'
      doc: 'Miax Pearl Equities'
    0x49:
      id: 'nasdaq_ise'
      doc: 'Nasdaq Ise'
    0x4a:
      id: 'cboe_edga_exchange'
      doc: 'Cboe Edga Exchange'
    0x4b:
      id: 'cboe_edgx_exchange'
      doc: 'Cboe Edgx Exchange'
    0x4c:
      id: 'long_term_stock_exchange'
      doc: 'Long Term Stock Exchange'
    0x4d:
      id: 'nyse_chicago'
      doc: 'Nyse Chicago'
    0x4e:
      id: 'new_york_stock_exchange'
      doc: 'New York Stock Exchange'
    0x50:
      id: 'nyse_arca'
      doc: 'Nyse Arca'
    0x51:
      id: 'nasdaq'
      doc: 'Nasdaq'
    0x55:
      id: 'members_exchange'
      doc: 'Members Exchange'
    0x56:
      id: 'investors_exchange'
      doc: 'Investors Exchange'
    0x58:
      id: 'nasdaq_phlx'
      doc: 'Nasdaq Phlx'
    0x59:
      id: 'cboe_byx_exchange'
      doc: 'Cboe Byx Exchange'
    0x5a:
      id: 'cboe_bzx_exchange'
      doc: 'Cboe Bzx Exchange'
  scope:
    0x4d:
      id: 'purge_all_orders_for_specified_mpid'
      doc: 'Purge All Orders For Specified Mpid'
  action:
    0x42:
      id: 'block_only'
      doc: 'The System Will Reject All New Orders'
    0x4d:
      id: 'mass_cancel_only'
      doc: 'The System Will Masscancel All Open Orders New Orders Can Be Accepted'
    0x58:
      id: 'block_and_mass_cancel'
      doc: 'Block And Mass Cancel'
    0x52:
      id: 'remove_blocking_for_the_specified_scope'
      doc: 'Remove Blocking For The Specified Scope'
  login_status:
    0x20:
      id: 'successful'
      doc: 'Successful'
    0x53:
      id: 'invalid_trading_session_requested'
      doc: 'Invalid trading session requested for the Matching Engine'
    0x55:
      id: 'no_active_trading_session_exists'
      doc: 'No active trading session exists for the Matching Engine, Matching Engine unavailable'
    0x58:
      id: 'rejected'
      doc: 'Invalid Username/Computer ID combination'
    0x4e:
      id: 'invalid_start_sequence_number_requested'
      doc: 'Invalid start sequence number requested'
    0x49:
      id: 'incompatible_session_protocol_version'
      doc: 'Incompatible Session protocol version'
    0x41:
      id: 'incompatible_application_protocol_version'
      doc: 'Incompatible application protocol version'
    0x4c:
      id: 'request_rejected_because_client_already_logged_in'
      doc: 'Request rejected because client already logged in'
  logout_reason:
    0x20:
      id: 'graceful_logout'
      doc: 'Graceful Logout'
    0x42:
      id: 'bad_packet'
      doc: 'Bad SesM packet'
    0x4c:
      id: 'timed_out'
      doc: 'Timed out waiting for Login Packet'
    0x41:
      id: 'application_terminating_connection'
      doc: 'Application terminating connection'

